### ISSUE TITLE
[packagers] Brew packager is silently skipped if distribution file names do not end up with zip or jar

### ISSUE THREAD

**Issue by maciejwalkowiak** [jreleaser/jreleaser#1033]
When artifacts files do not end up with `zip` or `jar` (as described as required in [docs](https://jreleaser.org/guide/latest/configuration/packagers/homebrew.html)), publishing to Homebrew is just skipped without any error or warning message.

I believe there should be a warning explaining why brew packaging is skipped, or perhaps the whole release should fail.

**Comment by aalmiray** [comment]
The `trace.log` (also when running the tool in with `-g` or --debug`) prints out the following message when there are no matching artifacts (during validation):

```
- disabled because there were no matching artifacts
```

This message could be upgraded to a warning.
Automatically turning this warning into an error would result in incompatible behavior thus should be reserved for `2.x`. However, a strict mode could be added to JReleaser that results in warnings turned into errors. The strict mode would have to be explicitly enabled. In `2.x` strict _could_ become the default. WDYT?

**Comment by maciejwalkowiak** [comment]
To me this message is not self explanatory. ".. no matching artifacts" and then I think it would make sense to say conditions must be met that the artifact is matched, or what is wrong with current artifacts.

I think strict mode sound like a good idea - it should fail if there is any configuration mistake

**Comment by aalmiray** [comment]
At first I thought checking if strict mode is enabled by looking up a System property such as `jreleaser.strict`. However, that would set precedent for other settings that are already specified using command flags (CLI, Gradle) or goal/task properties (Maven, Gradle, Ant).

I suppose adding `--strict` (CLI, Gradle), `jreleaser.strict` (Maven, Gradle, Ant), and `<strict>` (Maven) would be consistent with other settings such as `dry-run`.

**Comment by maciejwalkowiak** [comment]
🚀

**Comment by aalmiray** [comment]
Released in v1.4.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.4.0
