### ISSUE TITLE
Commits that contain multiple line ending types are not split correctly

### ISSUE THREAD

**Issue by bdemers** [jreleaser/jreleaser#1042]
I found a few commits from dependabot that contain line endings with both a CR/LF and LF `\r\n` and `\n`.

The current splitting logic, splits on `\r\n` and falls back to `\n`, it should split on both.

Example:

```txt
This is my title <LF>
<LF>
This is my body text <CR><LF>
More body text
```

This results in the "title" being parsed as:

```txt
This is my title <LF>
<LF>
This is my body text
```

This results in a problem later on in the processing of changelog labels because the regex matching does NOT match multi-lines.

**Comment by aalmiray** [comment]
Released in v1.4.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.4.0
