### ISSUE TITLE
[packagers] Support building multiplatform Docker images

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1046]
https://github.com/docker/buildx

Raised by @gotson at https://github.com/jreleaser/jreleaser/discussions/1045

**Comment by gotson** [comment]
so quick ! 🚀

**Comment by aalmiray** [comment]
Be aware than an update is coming in a few hours. Only JAVA_BINARY and SINGLE_JAR distros may be used with buildx as there's no guarantee other distros produce multi-arch compatible binaries.

**Comment by aalmiray** [comment]
Released in v1.4.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.4.0
