### ISSUE TITLE
GitHub docs are stale for GitHub.owner

### ISSUE THREAD

**Issue by bitspittle** [jreleaser/jreleaser#1052]
After upgrading from 1.0.0 to 1.3.1 I saw that GitHub owner was now gone. So I went to:

https://jreleaser.org/guide/latest/configuration/release/github.html

to see what it changed to, but the docs still reference `owner` there.

Note there may be other stale fields, I didn't look too carefully.

**Comment by aalmiray** [comment]
Please file doc issues at jreleaser/jreleaser.github.io

**Comment by aalmiray** [comment]
The only reference I can see to "owner" in the Gradle tab is

```
      // Username used for authoring commits. Must have write access to the repository.
      // If left unspecified, the `JRELEASER_GITHUB_USERNAME`
      // environment variable must be defined.
      // Defaults to the repository's owner.
      //  
      username = 'duke'
```

Is this the one you saw?

**Comment by bitspittle** [comment]
Apologies for the confusion. Here's what I'm seeing:

![jreleaser-github](https://user-images.githubusercontent.com/43705986/202050609-f81495e5-3866-4e69-a484-ccce2613a677.png)

I believe that property is now called `repoOwner`, not `owner`

**Comment by bitspittle** [comment]
Ah, OK, after rereading your reply, I see that there's a separate Gradle tab. On the Gradle tab, it is correct.

Closing this issue.
