### ISSUE TITLE
[announce] Follow ups posts ion Mastodon should be marked as unlistet

### ISSUE THREAD

**Issue by McPringle** [jreleaser/jreleaser#1057]
**Is your feature request related to a problem? Please describe.**
Using threaded status on Mastodon, all posts are public. So all posts show up on all timelines equally.

**Describe the solution you'd like**
The first post should be public. All following posts (threaded answers) should be posted as "unlisted". This will result in a "real thread". That is the recommended behavior of many instances.

- Post 1 (public) -> visible in all timelines
  - Post 2 (unlisted) -> visible when opening Post 1
  - Post 3 (unlisted) -> visible when opening Post 1

**Comment by aalmiray** [comment]
See `visibility` property that may be set as part of the data payload https://docs.joinmastodon.org/methods/statuses/

**Comment by aalmiray** [comment]
Matter of fact, we could set the `visibility` field automatically as `unlisted` when creating a new `Status` object with whose `replyToId` is non null. IOW there's no need to expose a user facing configurable setting for this property at the moment.

**Comment by aalmiray** [comment]
Released in v1.4.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.4.0
