### ISSUE TITLE
github.token must not be blank

### ISSUE THREAD

**Issue by jruaux** [jreleaser/jreleaser#106]
First of all thank you for creating this project. I have been using it to release [RIOT](https://github.com/redis-developer/riot) and it has been great!
I have the following issue with the gradle plugin:

```
❯ ./gradlew jreleaseFullRelease

> Task :jreleaserFullRelease FAILED
[INFO]  Loading properties from /Users/jruaux/.jreleaser/config.properties
[WARN]  Properties source /Users/jruaux/.jreleaser/config.properties does not exist
[INFO]  Validating configuration
[ERROR] == JReleaser ==
[ERROR] github.token must not be blank. Alternatively define a JRELEASER_GITHUB_TOKEN environment variable.
[ERROR] github.token must not be blank. Alternatively define a JRELEASER_GITHUB_TOKEN environment variable.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jreleaserFullRelease'.
```

I do have github.token defined in my global gradle.properties:
```
❯ more ~/.gradle/gradle.properties
github.token=...
```

Everything works fine when I set the JRELEASER_GITHUB_TOKEN env variable.

### Environment Information

- **Operating System:**: macOS
- **JReleaser Version**: 0.2.0
- **JDK Version**: openjdk 11.0.10 2021-01-19

Any idea what I could be doing wrong?

Thanks!

**Comment by aalmiray** [comment]
Thanks! I see what's going on here, the error message is misleading depending on how you interpret it.

The error message was written with the standalone configuration format in mind, however from a Gradle perspective it implies that a `github.token` property should be defined when in reality the what must happen is either `jreleaser.release.github.token = ...` is set in the build file (not as a property in `gradle.properties` not as a command line option) or `jreleaser { release { github.token = ... } } }` is set in the build file. Both of these options are bad as there's a secret in plain sight.

Now, you have the option to define environment variables as needed, or place secrets at another special location configured in `jreleaser { environment { variables = ... } }` as explained at https://jreleaser.org/guide/latest/configuration/environment.html

I wonder, if tool specific properties sources (`~/.gradle/gradle.properties` for Gradle, `~/m2/settings.xml` for Maven) should be taken into account by `environment:` when resolving variables.

**Comment by jruaux** [comment]
Thanks for the quick response. I'll rely on env variables for now.
For what it's worth some gradle plugins (bintray, [github-release-gradle-plugin](https://github.com/BreadMoirai/github-release-gradle-plugin)) expose the Gradle project in their configuration so you can do something like:
`token = project.hasProperty('github.token') ? project.property('github.token') : System.getenv('GITHUB_TOKEN')`

**Comment by aalmiray** [comment]
Right, except that when the Gradle project context is no longer available when the JReleaser model is evaluated and validated. It's just a plumbing issue that needs to be resolved in some other way.
