### ISSUE TITLE
[announce] Use environment variables for Zulip's account and apiHost properties

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1107]
Key names should be:
- `JRELEASER_ZULIP_ACCOUNT`
- `JRELEASER_ZULIP_APIHOST`

Additionally, `account` should be rendered as a secret when invoking the `config` command.

**Comment by manikmagar** [comment]
Change looks simple. Is there any specific test strategy for announcers? Couldn't see any unit tests around it.

**Comment by aalmiray** [comment]
Yes, it's a simple change. No tests cases in general but the use of a WireMock extension is encouraged 😅

**Comment by aalmiray** [comment]
Released in v1.5.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.5.0
