### ISSUE TITLE
[changelog] Contributor username lookup

### ISSUE THREAD

**Issue by manikmagar** [jreleaser/jreleaser#1112]
Discussed in #1111 

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Find a user who -
1. Doesn't have a public email On Github profile
2. Display name (eg. Manik Magar) has more than one profile on Github.

If that user has a commit on the repo, observe his entry in the change log.

### Expected Behaviour

When generating the changelog, the contributor's correct username is added.

### Actual Behaviour

Looks like it is searching by Author's name - 'Kevin King' (see web query [here](https://github.com/search?l=&p=7&q=fullname%3AKevin+King+type%3Auser&type=Users)) and just picked up the first user found
https://github.com/jreleaser/jreleaser/blob/main/sdks/jreleaser-github-java-sdk/src/main/java/org/jreleaser/sdk/github/XGithub.java#L103-L111 -

But that's not the Kevin who committed the change :). This user also has [a private github email](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#:~:text=GitHub%20account.%22-,Note%3A,-If%20you%20created) id - [ID+USERNAME@users.noreply.github.com](mailto:ID+USERNAME@users.noreply.github.com). The API documentation states that users having "Public email" listed on their profile can only be searched using email and since there is no public email listed here, search by email id is not useful. Searching by names as seen below can result in unexpected results.

### From the discussion -

Lookup should - 
> 1. check email, if private then extract username. done.
> 2. search by email. If found use name.
> 3. use name as extracted from commit message (this would need to be recorded as well. I think only the email is recorded at the moment.

**Comment by aalmiray** [comment]
The `ChangelogGenerator.User` class assumes the resolved user has an URL. But this may not be the case when the returned username is from a private email nor when the plain name is returned.

https://github.com/jreleaser/jreleaser/blob/6d5b0bcbda03dd8fda5addd8ae0ceef0bd9859c8/sdks/jreleaser-git-java-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java#L860

The code must check if `username`, `name`, and `url` are properly set before using their values. Return empty strings when that's not the case.

**Comment by aalmiray** [comment]
Released in v1.4.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.4.0
