### ISSUE TITLE
[packager] Install through Chocolatey leads to error

### ISSUE THREAD

**Issue by jeffmaury** [jreleaser/jreleaser#1126]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. choco install jreleaser
2. jreleaser

### Expected Behaviour

jreleaser should execute

### Actual Behaviour

```
La ligne entrée est trop longue.
La syntaxe de la commande n’est pas correcte.
```

which is the French version for
```
The input line is too long.
The command syntax is not correct.
```
### Environment Information

- **Operating System**: Win11Pro
- **JReleaser Version:** 1.3.1
- **JDK Version:** 17.0.4.1

**Comment by aalmiray** [comment]
Released in v1.4.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.4.0
