### ISSUE TITLE
[changelog] `NullPointerException` when `changelog.append.enabled=true` but target file doesn't exist

### ISSUE THREAD

**Issue by gotson** [jreleaser/jreleaser#1139]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. set `changelog.append.enabled` to `true`
2. do not have a `CHANGELOG.md` file in the project root
3. run `mvn jreleaser:changelog`

### Expected Behaviour

Not sure what should happen:
- either a new `CHANGELOG.md` file is created with the changelog content
- or an error is thrown
but definitely not a `NullPointerException` !

### Actual Behaviour

Maven plugin crashes.

### Environment Information

- **Operating System**: MacOS
- **JReleaser Version:** 1.4.0
- **JDK Version:** 11

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

[trace.log](https://github.com/jreleaser/jreleaser/files/10335221/trace.log)

**Comment by aalmiray** [comment]
A new CHANGELOG.md should be created as a result.

**Comment by aalmiray** [comment]
FWIW I think this bug was found and fixed right after 1.4.0 during the Sonar cleanup. Must verify this claim.

**Comment by aalmiray** [comment]
Fixed with https://github.com/jreleaser/jreleaser/commit/dc3054cb25327b84c7c86a8f2fd3621b08bef70d
