### ISSUE TITLE
[changelog] `previousTagName` is empty when generating changelog append

### ISSUE THREAD

**Issue by gotson** [jreleaser/jreleaser#1143]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. configure `changelog.append.title` to `"## [{{projectVersion}}]({{repoUrl}}/compare/{{previousTagName}}...{{tagName}}) ({{#f_now}}YYYY-MM-dd{{/f_now}})"`
2. `gradlew jreleaserChangelog`

### Expected Behaviour

The appended `CHANGELOG.md` contains `https://github.com/gotson/komga/compare/v0.157.5...v0.157.6` for the compare URL.

### Actual Behaviour

The appended `CHANGELOG.md` contains `https://github.com/gotson/komga/compare/...v0.157.6` for the compare URL.

### Environment Information

- **Operating System**: macOS
- **JReleaser Version:** 1.4.0
- **JDK Version:** 11

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

[trace.log](https://github.com/jreleaser/jreleaser/files/10349288/trace.log)

**Comment by gotson** [comment]
I checked in the regular changelog too (not just the append), and it doesn't work either.

**Comment by aalmiray** [comment]
Released in v1.5.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.5.0
