### ISSUE TITLE
[changelog] `{{changelogChanges}}` and `{{changelogContributors}}` not available for changelog append

### ISSUE THREAD

**Issue by gotson** [jreleaser/jreleaser#1144]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. set `changelog.append.content` to `{{changelogChanges}} {{changelogContributors}}`
2. run `jreleaserChangelog`

### Expected Behaviour

The appended `CHANGELOG.md` should contain changelog changes and contributors.

### Actual Behaviour

The appended `CHANGELOG.md` does not contain anything.

### Environment Information

- **Operating System**: macOS
- **JReleaser Version:** 1.4.0
- **JDK Version:** 11

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

[trace.log](https://github.com/jreleaser/jreleaser/files/10349314/trace.log)

**Comment by aalmiray** [comment]
Released in v1.5.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.5.0
