### ISSUE TITLE
[docker] buildx always check for a builder named `jreleaser`

### ISSUE THREAD

**Issue by gotson** [jreleaser/jreleaser#1146]
I haven't tested this, only noticed in the code while trying to figure out how to use JReleaser along with https://github.com/docker/setup-buildx-action

This [line](https://github.com/jreleaser/jreleaser/blob/1d3f651392e60c22e29f85a5f580e8db61ef9745/core/jreleaser-engine/src/main/java/org/jreleaser/packagers/DockerPackagerProcessor.java#L244) seems to indicate that JReleaser expects a builder with the name `jreleaser`.

I understand that the default `buildx.createBuilderFlags` is `['--name', 'jreleaser', '--driver', 'docker-container', '--bootstrap', '--use']`, and as such the buildx builder should be called `jreleaser`, but if one customizes the `createBuilderFlags`, then JReleaser would recreate a builder, as the name would not necessarily match `jreleaser` anymore.

**Comment by gotson** [comment]
Side question: would it be possible to disable the buildx builder creation entirely ? Since a builder can be registered for use, JReleaser could then use what's setup already, and not attempt to create a builder.

Typically i would like to use https://github.com/docker/setup-buildx-action but the action doesn't allow for setting the builder's name. If i could tell JReleaser not to create a builder, but use the one that i created, i would much prefer.

**Comment by aalmiray** [comment]
Released in v1.5.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.5.0
