### ISSUE TITLE
[deploy] Remove GPG public key requirement to release to maven central

### ISSUE THREAD

**Issue by ttddyy** [jreleaser/jreleaser#1158]
I have adapted my project [datasource-micrometer](https://github.com/jdbc-observations/datasource-micrometer) to use JReleaser, and this is one of the feedback.

The project is a java library and publishing to maven central.
Prior to switching JReleaser, I was using the `maven deploy` in github action, like [the one described in the github documentation page](https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven#publishing-packages-to-the-maven-central-repository).

With the github approach, the parameters I need to pass to the workflow are:
- `GPG_PASSPHRASE`
- `GPG_SECRET_KEY`
- `OSSRH_PASSWORD`
- `OSSRH_USERNAME`

But with the JReleaser approach, based on the [documentation](https://jreleaser.org/guide/latest/examples/maven/maven-central.html), I need to also provide `GPG_PUBLIC_KEY` which I'm not sure where it is actually used.
(Probably not used, but since signing is enabled, even though the log shows `[sign] No files configured for signing. Skipping`, the precondition validation fails without it).

It would be better not to require the public key when publishing the jars to maven central via OSS sonatype.

**Comment by aalmiray** [comment]
IIRC secret key is needed for signing while public is used for verifying signatures. All maven deployers have an option to skip signing (during deployment) assuming signatures were also staged. What could be added is an option to skip verifying signatures in which case public keys might be skipped.

Also note that the message `[sign] No files configured for signing. Skipping` appears for distribution artifacts which I'd assume you have none at the moment.

**Comment by aalmiray** [comment]
Released in v1.5.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.5.0
