### ISSUE TITLE
[core] Let active value be defined via environment variables

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1175]
Affects every model object that defines an `active` property.

**Comment by aalmiray** [comment]
@gsmet this should let you define a value for `active` properties suing System props or Env vars.

**Comment by gsmet** [comment]
@aalmiray oh that is amazing, thanks.

**Comment by aalmiray** [comment]
Released in v1.5.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.5.0
