### ISSUE TITLE
[core] Allow artifacts to be optional

### ISSUE THREAD

**Issue by crschnick** [jreleaser/jreleaser#1183]
Some artifacts that I use in distributions are intended to be optional, for example a changelog file. However, it is currently not possible to designate them as such and as a result I have to use constructs like this:

      if (file("$projectDir/changelogs/${version}.md").exists()) {
          artifact {
              distributionType = 'BINARY'
              path = "$projectDir/changelogs/${version}.md"
              extraProperties.put('universal', true)
              transform = 'changelog.md'
          }
      }

It would be nicer to just have an option to set `optional = true`. Also, there isn't really a matching distribution type for text files, so I chose binary here.

**Comment by aalmiray** [comment]
Adding an extra property with key `optional` sounds like a good idea. 

You may use the [Files](https://jreleaser.org/guide/latest/reference/files.html) section for any other artifact that does not match a distribution type.

**Comment by aalmiray** [comment]
Released in v1.5.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.5.0
