### ISSUE TITLE
[packager] Homebrew release no longer working after update to 1.5.0

### ISSUE THREAD

**Issue by wimdeblauwe** [jreleaser/jreleaser#1229]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

I have run a release of my project ttcli before and that worked fine to also release to Homebrew. See https://github.com/wimdeblauwe/ttcli/actions/runs/4212064921/jobs/7310896972 for an example of a working build.

However, when I released yesterday (after updating from 1.3.1 to 1.5.0), there has been no release to Homebrew. See https://github.com/wimdeblauwe/ttcli/actions/runs/4307699121/jobs/7513285490 for the logs of the build that did not trigger a release to Homebrew. There is no error or warning indicating that something was wrong.

### Expected Behaviour

Release to homebrew of my package.

### Actual Behaviour

No release to homebrew, no errors or warnings in the build.

### Environment Information

- **Operating System**: GitHub Action
- **JReleaser Version:** 1.5.0
- **JDK Version:** 17

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

**Comment by aalmiray** [comment]
Confirmed. It works til `1.4.0` but `1.5.0` disables the brew packager.
The problem is `NATIVE_IMAGE` was deprecated in favor of `BINARY` in `v1.4.0`. There's even a warning on the console when running this version. However, the warning is gone in `v1.5.0` (that's a bug).

Workaround is to change `<type>NATIVE_IMAGE</type>` to `<type>BINARY</type>`.

**Comment by wimdeblauwe** [comment]
Can confirm the change from `NATIVE_IMAGE` to `BINARY` makes it work again. Thanks!

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.5.1` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.5.1))
