### ISSUE TITLE
[changelog] ClassCastException when changelog extraProperties "categorizeScopes" is set and a commit is not conventional

### ISSUE THREAD

**Issue by gotson** [jreleaser/jreleaser#1230]
I also noticed that we may have the wrong regex for conventional commit type: https://github.com/jreleaser/jreleaser/blob/36b04bf3818c6233288b29626601f323ed0ae461/sdks/jreleaser-git-java-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java#L700-L700

I was trying to use `i18n` as type, but it's not allowed.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. have a commit that is not conventional in the git history
2. set `changelog.extraProperties.categorizeScopes=true`
3. run `jreleaserChangelog`

### Expected Behaviour

Changelog should be generated

### Actual Behaviour

JReleaser crashes with 

### Environment Information ClassCastException

- **Operating System**: macOS
- **JReleaser Version:** 1.5.0
- **JDK Version:** 11

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

[trace.log](https://github.com/jreleaser/jreleaser/files/10878640/trace.log)

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.5.1` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.5.1))
