### ISSUE TITLE
[packager] Docker fails with cleanup error: no builder "jreleaser" found

### ISSUE THREAD

**Issue by gotson** [jreleaser/jreleaser#1244]
I am trying the latest 1.6.0-SNAPSHOT that fixes all the docker issues i raised in the past week. All of it works, thanks a lot ! However i still have an issue in the cleanup process.

Could be linked to #1168

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. run `jreleaserPublish`
2. the error happens after the publishing is complete

### Expected Behaviour

No errror should happen

### Actual Behaviour

Error in the logs

### Environment Information

- **Operating System**: macOS Ventura
- **JReleaser Version:** 1.6.0-SNAPSHOT
- **JDK Version:** 17

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

[trace.log](https://github.com/jreleaser/jreleaser/files/10917609/trace.log)

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.5.1` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.5.1))
