### ISSUE TITLE
[templates] Apply shellcheck to launcher templates

### ISSUE THREAD

**Issue by bmarwell** [jreleaser/jreleaser#1246]
Just spotted the template:
https://github.com/jreleaser/jreleaser/blob/7ed38b21da3d1f4ceafb2b2eeb8192580191696f/core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/java-archive/java-archive/bin/launcher.tpl

Running shellcheck yields some interesting results. E.G. backticks are being used over the `$()` alternative which can do better escaping.

### Task List

- [X] Steps to reproduce provided
Run shellcheck
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. run shellcheck

### Expected Behaviour

no issues found

### Actual Behaviour

Some issues found

### Environment Information

- **Operating System**: Linux or Mac
- **JReleaser Version:** git
- **JDK Version:** n/a

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.5.1` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.5.1))
