### ISSUE TITLE
[deploy] Support turning on checksums

### ISSUE THREAD

**Issue by ge0ffrey** [jreleaser/jreleaser#1290]
Add an option to turn on checksums if applyMavenCentralRules is set to false, just like signing. There must be an additional property to turn on/off checksums independently.

For example:

```
            <deploy>
              <maven>
                <nexus2>
                  <maven-central>
                    <applyMavenCentralRules>false</applyMavenCentralRules>
                    <sign>true</sign>
                    <checksum>true</checksum>
```

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.6.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.6.0))
