### ISSUE TITLE
[release] Latest early-access release uploads corrupt zip files

### ISSUE THREAD

**Issue by jruaux** [jreleaser/jreleaser#1306]
The latest early-access release uploads zip files to github in a format not understood by unzip and other decompression utilities. 

<img width="378" alt="Screenshot 2023-03-30 at 9 00 03 AM" src="https://user-images.githubusercontent.com/1628034/228895689-a767159c-2d22-455e-bae5-09bbffc57eeb.png">

Switching to `latest` jreleaser instead of `early-access` fixed the problem.

**Comment by aalmiray** [comment]
Fix is already on the way https://github.com/jreleaser/jreleaser/commit/0950b0cf82421da7f39719626f873c6656070f67

**Comment by aalmiray** [comment]
Fixed. Sorry for the inconvenience 😓
