### ISSUE TITLE
[packagers] choco packager fails when artifacts do not contain arch identifier

### ISSUE THREAD

**Issue by crschnick** [jreleaser/jreleaser#1312]
I played around with choco as a packager and encountered the issue because my artifacts just had an `os='windows'` identifier without arch. The log was not useful for debugging as the exception stack trace was swallowed.

I did some digging and found out that it fails here with an OOB: https://github.com/jreleaser/jreleaser/blob/9d7e2564f2ff7d70c8a3e7c072befc6dfd104e27/api/jreleaser-utils/src/main/java/org/jreleaser/util/PlatformUtils.java#L121

**Comment by aalmiray** [comment]
Workaround is to define a full platform literal such as "`windows-x86_64`".

**Comment by crschnick** [comment]
The main issue here for me was that somehow the stack trace was swallowed by jreleaser. It somehow interpreted the OOB as a configuration error and just printed a message.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.6.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.6.0))
