### ISSUE TITLE
[packagers] Chocolatey requires project tags to be non empty but jreleaser is not checking that

### ISSUE THREAD

**Issue by crschnick** [jreleaser/jreleaser#1313]
The `<tags></tags>` entry in the nuspec file must contain at least one tag to publish it to the repository, so jreleaser should maybe warn if that is missing.

**Comment by aalmiray** [comment]
Add a check at https://github.com/jreleaser/jreleaser/blob/966a2e1b73fdb614a6aa6a52c9e3145be8bc3d56/core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/packagers/ChocolateyPackagerValidator.java#L247 for `distribution.tags`. Raise a configuration error if it's empty.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.6.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.6.0))
