### ISSUE TITLE
[gradle] "assemble dist" task should be configurable or at least disableable

### ISSUE THREAD

**Issue by bitspittle** [jreleaser/jreleaser#1316]
Specifically, I'm talking about this: https://github.com/search?q=repo%3Ajreleaser%2Fjreleaser%20ASSEMBLE_DIST_TASK_NAME&type=code

I use the shadow plugin to assemble my binaries (as a way to do dead-code elimination). I then uploaded those to github.

I run `assembleShadowDist` to build them. I configured those to write to the same location that `assembleDist` uses.

Now, when I run `jreleaserPublish`, it wipes out my local files, replaces them with non-shadowed versions, and then recalculates a hash. This hash value is totally different from the artifact I want people to download. So when it uploads all the various package managers, it uses a hash value that's different from the artifacts on GitHub.

What I want is either...

* A way to override what Jreleaser thinks the name of the "assemble distribution" task should be
* A way to tell Jreleaser that I'll be the one putting zip files in the distribution folder, before I call jreleaserPublish, so it doesn't need to do anything for me.

Of course, happy to discuss any other solutions proposed as well, or maybe there's already a way to do what I want which I overlooked (i.e. user error!)

**Comment by bitspittle** [comment]
That works for me. Thank you for the quick reply and turnaround (as always)!

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.6.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.6.0))
