### ISSUE TITLE
[packagers] Flatpak .yml file is missing sources

### ISSUE THREAD

**Issue by crschnick** [jreleaser/jreleaser#1330]
In the generated file `io.xpipe.app.yml`, some files are not included under sources which results in the install failing. I added this manually and it works:

    sources:
      - type: file
        path: io.xpipe.app.desktop

**Comment by aalmiray** [comment]
Could you provide a bit more detail such as:
- distribution type
- stereotype

If possible, linking to the repository that contains the configuration _or_ pasting the configuration in this issue would be better.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.6.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.6.0))
