### ISSUE TITLE
[packagers] Flatpak installs executables wrongly

### ISSUE THREAD

**Issue by crschnick** [jreleaser/jreleaser#1332]
The generated install commands look like this:

    build-commands:
      - install -Dm755 xpiped /app/xpiped
      - install -Dm644 extensions/base/base.jar /app/extensions/base/base.jar
      ...

However, the xpiped executable is located in the bin directory now (as this is what the distribution requires), so the installation should look like this:

    build-commands:
      - install -Dm755 bin/xpiped /app/bin/xpiped
      - install -Dm644 extensions/base/base.jar /app/extensions/base/base.jar

**Comment by aalmiray** [comment]
Fixed with https://github.com/jreleaser/jreleaser/commit/1e86caa428ce83b0bb9809559b26f4ba7c017b1e
