### ISSUE TITLE
[jdks] Add option to disable unpacking

### ISSUE THREAD

**Issue by charphi** [jreleaser/jreleaser#1366]
**Is your feature request related to a problem? Please describe.**
`jdks:setup-disco` and `jdks:setup-jdks` automaticaly unpack JDKs.
My problem is that the unpacking fails on my _corporate_ Windows laptop with any Linux JDK. The failure is caused by an attempt to create symbolic links. I know that it can be solved by enabling Developer Mode on Windows but I'm not allowed to do that.

**Describe the solution you'd like**
Add an option to disable auto unpacking so I can at least download a Linux JDK.

**Describe alternatives you've considered**
- Enable the [Developer Mode on Windows](https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development): not possible in my case.
- Use the [selectCurrentPlatform](https://jreleaser.org/guide/latest/tools/jreleaser-maven.html#_environment_variables) setting: should be ok, not tested yet.
- Never perform a release from the problematic laptop: I'm using GitHub Actions to do the release but I would prefer to test it (in dry mode) before pushing the code.

**Additional context**
None.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.6.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.6.0))
