### ISSUE TITLE
[maven] JReleaserConfigMojo should have a skip property

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#137]
Useful when the mojo is configured on a child project inside a multi-project build as that allows invoking the goal using a subset if the Reactor.

Suggested by @bmarwell

**Comment by aalmiray** [comment]
Hmm it looks like the property does exist

https://github.com/jreleaser/jreleaser/blob/main/plugins/jreleaser-maven-plugin/src/main/java/org/jreleaser/maven/plugin/JReleaserConfigMojo.java#L36-L41

It's even documented

https://jreleaser.org/guide/latest/tools/jreleaser-maven.html#_jreleaserconfig

**Comment by aalmiray** [comment]
This is not a bug.

**Comment by bmarwell** [comment]
No, this is a bug (probably): https://github.com/jreleaser/jreleaser/issues/140 :) 
I think I didn't describe it well on twitter which led you to opening this  issue. Please excuse my brevity on twitter. I hope I got it right in the other issue.
