### ISSUE TITLE
[packagers] Homebrew cask does not apply all properties

### ISSUE THREAD

**Issue by crschnick** [jreleaser/jreleaser#1370]
With 1.6.0, I now try to create a homebrew cask again, but it seems like the properties that I set under `cask` do not get applied consistently and revert to the defaults. It is essentially the same issue like #1323 where it is correct in one section in the model but incorrect in another.

**Comment by aalmiray** [comment]
Hmm in which case I suppose setting values under `distribution` instead of `packagers` would be a workaround.

**Comment by crschnick** [comment]
Alright that works I guess.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.7.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.7.0))
