### ISSUE TITLE
[packagers] choco bucket action fails

### ISSUE THREAD

**Issue by crschnick** [jreleaser/jreleaser#1391]
I tried to push a new version via a choco bucket repository, but the workflow generated by the jreleaser fails when setting up dotnet. 

This is the generated workflow file:

    name: Push-installer
    
    on:
      push:
        tags:
          - '*'
        branches-ignore:
          - '**'
    
    jobs:
      push:
        runs-on: windows-latest
        
        steps:
          - uses: actions/checkout@v3
          
          - uses: actions/setup-dotnet@v3
            with:
              dotnet-version: '6.0.16'
    
          - name: Find package
            shell: bash
            run: |
              echo "PACKAGE_NAME=$(ls installer/*.nuspec)" >> $GITHUB_ENV
    
          - name: Pack
            shell: powershell
            run: |
              choco pack ${{ env.PACKAGE_NAME }}
    
          - name: Publish
            shell: powershell
            run: |
              choco apikey -k ${{ secrets.CHOCOLATEY_API_KEY }} -s https://push.chocolatey.org/
              choco push $(ls *.nupkg | % {$_.FullName}) -s https://push.chocolatey.org/
    

[3_Run actionssetup-dotnet@v3.txt](https://github.com/jreleaser/jreleaser/files/11525029/3_Run.actionssetup-dotnet%40v3.txt)

**Comment by aalmiray** [comment]
Fixed with https://github.com/jreleaser/jreleaser/commit/053ec73417b112f65d386adba6daf3db05695c7c

Workaround: downgrade to an earlier version of .Net

**Comment by crschnick** [comment]
Is the milestone due date the scheduled release date of 1.7? So I know whether I should apply that workaround by myself or not.

**Comment by aalmiray** [comment]
Yes, that is correct.
