### ISSUE TITLE
[maven] Cannot skip config goal in reactor

### ISSUE THREAD

**Issue by bmarwell** [jreleaser/jreleaser#140]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a reactor pom. Simple root and 1 module is sufficient.
2. Add this configuration to the root pom:
```xml
 <profile>
      <id>app</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>

      <properties>
        <plugin.jreleaser.skip>true</plugin.jreleaser.skip>
      </properties>

      <build>
        <plugins>
          <plugin>
            <groupId>org.jreleaser</groupId>
            <artifactId>jreleaser-maven-plugin</artifactId>
            <version>0.3.0</version>
            <configuration>
              <skip>${plugin.jreleaser.skip}</skip>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
```
3. start mvn jreleaser:config -Papp

### Expected Behaviour

Root pom will not be evaluated for parameters and the plugin is complaining about the reactor module not being configured.

### Actual Behaviour

Root pom will not be executed successfully because there is no configuration in the root pom:

```
$ mvn jreleaser:config -Papp
# ...
[INFO] emu2api ............................................ FAILURE [  2.528 s]
# … other artifacts
# artifact with the jreleaser configuration:
[INFO] emu2api :: server :: meecrowave .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.876 s
[INFO] Finished at: 2021-05-11T09:28:10+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jreleaser:jreleaser-maven-plugin:0.3.0:config (default-cli) on project emu2api: The parameters 'jreleaser' for goal org.jreleaser:jreleaser-maven-plugin:0.3.0:config are missing or invalid -> [Help 1]
```

I expected the config will be skipped here and printed only for the server module.

### Environment Information

- **Operating System**: Ubuntu 20.04
- **JReleaser Version:** 0.3.0
- **JDK Version:** JDK 11 OpenJ9 and Hotspot

**Comment by bmarwell** [comment]
ah, this is a problem: https://github.com/jreleaser/jreleaser/blob/main/plugins/jreleaser-maven-plugin/src/main/java/org/jreleaser/maven/plugin/AbstractJReleaserMojo.java#L97

For reactor projects, we need to set the multimodule base directory here, similar to https://stackoverflow.com/a/49528226/1549977.

**Comment by bmarwell** [comment]
> `${maven.multiModuleProjectDirectory}` requires the existence of `.mvn`

I honestly don't think this is true (anymore).

@aalmiray  you resolved the wrong issue with your commit.

**Comment by aalmiray** [comment]
Perhaps. Certainly it's not the case for Maven 3.8.1 which I tested with and without `.mvn`. Might be an issue for older versions.
