### ISSUE TITLE
[packagers] Launch scripts for SINGLE_JAR scoop distribution fails

### ISSUE THREAD

**Issue by charphi** [jreleaser/jreleaser#1419]
### Steps to Reproduce

1. Release SINGLE_JAR with scoop distribution
2. Install the released SINGLE_JAR with scoop

### Expected Behaviour

Installation should work.

### Actual Behaviour

Installation fails on `pre_install` script with a message that complains about an invalid token.

### Environment Information

- **Operating System**: Windows 10
- **JReleaser Version:** 1.5.1
- **JDK Version:** -

### Some more details

You can find an example at https://github.com/nbbrd/scoop-nbbrd/commit/bf5d82bf98727eb12d6a850ba3059ba45431f760 
The problem comes from missing double quotes around `distributionArtifactFile`.

The bug has been introduced by the commit cec0a8892a523e23b9c856b5498213045419bfe9 

And you can look at the specific line with this link: https://github.com/jreleaser/jreleaser/commit/cec0a8892a523e23b9c856b5498213045419bfe9#diff-b81e258f458c29cc59366a73132706108d0e434f3ce212dafe8966ffa12239cb

**Comment by aalmiray** [comment]
Scoop templates require additional escaped quotes around `\"$dir\\{{distributionArtifactFile}}\"` as shown at https://github.com/jreleaser/jreleaser/commit/cec0a8892a523e23b9c856b5498213045419bfe9#diff-b81e258f458c29cc59366a73132706108d0e434f3ce212dafe8966ffa12239cb

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.7.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.7.0))
