### ISSUE TITLE
[packagers] Invalid formula filename for SINGLE_JAR brew distribution

### ISSUE THREAD

**Issue by charphi** [jreleaser/jreleaser#1420]
### Steps to Reproduce

1. Release SINGLE_JAR brew distribution with an hyphen in the name (for example: `hello-nbbrd`)
2. Install the released SINGLE_JAR with brew

### Expected Behaviour

Installation should work.

### Actual Behaviour

Installation doesn't fail but install a previous version.

### Environment Information

- **Operating System**: macOS
- **JReleaser Version:** 1.5.1
- **JDK Version:** -

### Some more details

You can find an example at https://github.com/nbbrd/homebrew-tap/tree/master/Formula
Two files are available:
- `hello-nbbrd.rb` : a previous version created by an older version of JReleaser
- `hellonbbrd.rb` : the current version created by JReleaser v1.5.1

The problem might come from that commit (I'm not sure) introduced in v1.3.0: https://github.com/jreleaser/jreleaser/commit/256f444b0e1cea80d813cd9e27ed53f1ee70ae98

**Comment by aalmiray** [comment]
Could you share the configuration (both explicit in the DSL and resolved in `trace.log`)? I think we may have inadvertently changed the behavior in `1.3.0` as you noted.

**Comment by aalmiray** [comment]
The resolved formula file name should be the hyphenated (if needed), lowercase of the resolved formula name.
Fix should be applied to line 329 & 335

https://github.com/jreleaser/jreleaser/blob/c64c90f7bdacc9918f647198cf33ce5e97f6dbb8/core/jreleaser-engine/src/main/java/org/jreleaser/packagers/BrewPackagerProcessor.java#L326-L337

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.7.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.7.0))
