### ISSUE TITLE
[release] 422 Unprocessable Entity during Github release

### ISSUE THREAD

**Issue by triceo** [jreleaser/jreleaser#1421]
I get an exception when releasing a project using JReleaser Maven Plugin (running in Github Actions) configured like so:

      <plugin>
        <groupId>org.jreleaser</groupId>
        <artifactId>jreleaser-maven-plugin</artifactId>
        <version>1.6.0</version>
        <inherited>false</inherited>
        <configuration>
          <jreleaser>
            <signing>
              <active>ALWAYS</active>
              <armored>true</armored>
            </signing>
            <release>
              <github>
                <draft>true</draft>
                <overwrite>true</overwrite>
                <sign>true</sign>
                <issues>
                  <enabled>true</enabled>
                </issues>
                <changelog>
                  <formatted>ALWAYS</formatted>
                  <preset>conventional-commits</preset>
                  <contentTemplate>.github/workflows/release-changelog-template.md</contentTemplate>
                  <contributors>
                    <format>- {{contributorName}}{{#contributorUsernameAsLink}} ({{.}}){{/contributorUsernameAsLink}}</format>
                  </contributors>
                </changelog>
              </github>
            </release>
            <deploy>
              <maven>
                <nexus2>
                  <maven-central>
                    <active>ALWAYS</active>
                    
                    <verifyPom>false</verifyPom>
                    <url>https://s01.oss.sonatype.org/service/local</url>
                    <closeRepository>true</closeRepository>
                    <releaseRepository>false</releaseRepository>
                    <stagingRepositories>target/staging-deploy</stagingRepositories>
                    <artifactOverrides>
                      <artifactOverride>
                        <groupId>ai.timefold.solver</groupId>
                        <artifactId>timefold-solver-core</artifactId>
                        <sourceJar>false</sourceJar>
                        <javadocJar>false</javadocJar>
                      </artifactOverride>
                      <artifactOverride>
                        <groupId>ai.timefold.solver</groupId>
                        <artifactId>timefold-solver-spring-boot-starter</artifactId>
                        <sourceJar>false</sourceJar>
                        <javadocJar>false</javadocJar>
                      </artifactOverride>
                      <artifactOverride>
                        <groupId>ai.timefold.solver</groupId>
                        <artifactId>timefold-solver-ide-config</artifactId>
                        <sourceJar>true</sourceJar>
                        <javadocJar>false</javadocJar>
                      </artifactOverride>
                      <artifactOverride>
                        <groupId>ai.timefold.solver</groupId>
                        <artifactId>timefold-solver-webui</artifactId>
                        <sourceJar>true</sourceJar>
                        <javadocJar>false</javadocJar>
                      </artifactOverride>
                    </artifactOverrides>
                  </maven-central>
                </nexus2>
              </maven>
            </deploy>
          </jreleaser>
        </configuration>
      </plugin>

This is the last thing I get in the trace log:

    [DEBUG] fetching all branches on TimefoldAI/timefold-solver
    [DEBUG] looking up release with tag v0.10.0 at repository TimefoldAI/timefold-solver
    [DEBUG] fetching release on TimefoldAI/timefold-solver with tag v0.10.0
    [DEBUG] release v0.10.0 does not exist
    [DEBUG] creating release v0.10.0
    [DEBUG] tagging local repository with v0.10.0
    [DEBUG] creating release on TimefoldAI/timefold-solver with tag v0.10.0
    422 Unprocessable Entity
    org.jreleaser.sdk.commons.RestAPIException: 422: Unprocessable Entity
	at org.jreleaser.sdk.commons.ClientUtils.lambda$builder$1(ClientUtils.java:113)
        ...
    Caused by: org.jreleaser.sdk.commons.RestAPIException: 422: Unprocessable Entity
	at org.jreleaser.sdk.commons.ClientUtils.lambda$builder$1(ClientUtils.java:113)
	at feign.ResponseHandler.decodeError(ResponseHandler.java:136)
	at feign.ResponseHandler.handleResponse(ResponseHandler.java:70)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:114)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:96)
	at jdk.proxy3/jdk.proxy3.$Proxy31.createRelease(Unknown Source)
	at org.jreleaser.sdk.github.Github.createRelease(Github.java:334)
	at org.jreleaser.sdk.github.GithubReleaser.createRelease(GithubReleaser.java:352)
	at org.jreleaser.sdk.github.GithubReleaser.createRelease(GithubReleaser.java:235)
	... 35 more

This is the branch of our project that exhibits the issue:
https://github.com/TimefoldAI/timefold-solver/tree/triceo-releasetest

This was the run that failed:
https://github.com/TimefoldAI/timefold-solver/actions/runs/5332409307

**Comment by triceo** [comment]
Could it be that, while this new release is `v0.10.0`, the previous release was `0.9.38` (without the `v`), and therefore nothing could be found?

**Comment by aalmiray** [comment]
I believe I’ve seen this 422 error before at least once. I think it’s not related to a change in tag pattern as that affects changelog generation, not release publication.

**Comment by triceo** [comment]
I have just confirmed it is related to the tag.
When I specified `previousTagName`, the issue went away.
(Or it went away for a different environmental reason.)

**Comment by aalmiray** [comment]
Alright, thanks for verifying. I suppose there's a recent change that requires the tag pattern also during release 😅

**Comment by aalmiray** [comment]
FWIW `422` is returned when validation fails or the endpoint has been spammed -> https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release

The error occurs after setting initial parameters to create a release https://github.com/jreleaser/jreleaser/blob/c64c90f7bdacc9918f647198cf33ce5e97f6dbb8/sdks/jreleaser-github-java-sdk/src/main/java/org/jreleaser/sdk/github/GithubReleaser.java#L333-L346

Do you have access to the `trace.log` file when the release failed? Would like to find out what were the resolved values for the `release` section.

**Comment by triceo** [comment]
[trace.log](https://github.com/jreleaser/jreleaser/files/11823616/trace.log)

I've attached the trace log from that run.

**Comment by aalmiray** [comment]
I'm going on a limb here but I think setting the release to `draft` may be the cause. I have to test this theory. We used to rely on hub4j (external dependency) for interacting with the GitHub REST API. Recently we moved away from it and provided our own implementation. It's possible we missed something during that migration.

**Comment by aalmiray** [comment]
Looks like one probable cause for this error is performing a release targeting a branch that does not yet exist on the remote.
JReleaser must ensure that the target branch exists before creating a release.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.16.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.16.0))
