### ISSUE TITLE
[release] Support hosting the jreleaser configuration in a different repository than the one hosting the source code of the project

### ISSUE THREAD

**Issue by zakkak** [jreleaser/jreleaser#1441]
**Is your feature request related to a problem? Please describe.**
Assuming repository `A` is hosting the source code of the project, one might be interested in hosting the JReleaser configuration in a separate repository `B`. At the moment it looks like this is not an option. 

**Additional context**
AFAIU When running JReleaser it automatically detects the current commit hash of the repository `B` holding the configuration and passes it to the github API as the `target_commitish`. This results in GitHub returning a 422 error with the following message:

```
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Release",
      "code": "invalid",
      "field": "target_commitish"
    }
  ],
  "documentation_url": "https://docs.github.com/rest/releases/releases#create-a-release"
}
```

which indicates that (as expected) github failed to detect the commitish on the target repository `A`.

**Describe the solution you'd like**
I would suggest getting the `HEAD`'s hash from the `release.github.branch` of `release.github.host`/`release.github.owner`/`release.github.name` instead of trying to get it from the local repository. `git ls-remote` seems to be able to get the hash without cloning the repository.

**Describe alternatives you've considered**
There seems to be a **work around** for this issue by combining the options `-b` and `-c` as follows:

```
jreleaser release -c path/to/B/jreleaser.yml -b path/to/A
```

**Comment by aalmiray** [comment]
I believe the workaround is the proper way to handle this. JReleaser assumes the following when no additional parameters such as `-c` and `-b` are passed:

1. the current directory holds a configuration file (`jreleaser.[yml|json|toml]`)
2. the current directory is set to the `basedir`

If an explicit configuration file is set via `-c` or `--config-file` _then_ this file's containing directory will be set as `basedir` _unless_ and explicit basedir via `-b` or `--basedir` is set.

**Comment by aalmiray** [comment]
@zakkak is the suggested workaround sufficient or should additional code be added?

**Comment by zakkak** [comment]
Hi @aalmiray , unfortunately I haven't had the time (yet?) to actually transition Mandrel to JReleaser, but as far as I can tell the work around is sufficient.
