### ISSUE TITLE
[release] Better error handling for 422 error response from GitHub

### ISSUE THREAD

**Issue by zakkak** [jreleaser/jreleaser#1442]
**Is your feature request related to a problem? Please describe.**
When trying https://github.com/jreleaser/jreleaser/issues/1441 I noticed that JReleaser only reports a 422 error without any further details. Inspecting the stack trace one can only see which method resulted in the 422 error, but there is no access to the actual HTTP request nor to the message included in GItHub's response body.

**Describe the solution you'd like**
I would like to get some more information about what was the root cause that led to the 422 error, e.g., [was it a validation error](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release--status-codes), and if so which field was wrong?

**Describe alternatives you've considered**
Enable more detailed logging to see the POST request and manually run it using cURL.

**Additional context**
As pointed out by @aalmiray, JReleaser is [already doing all the error checking and has the necessary code to handle the error](https://github.com/jreleaser/jreleaser/blob/5dd77d716f4b50ccd57fef927e8ce5216db17712/sdks/jreleaser-github-java-sdk/src/main/java/org/jreleaser/sdk/github/GithubReleaser.java#L231-L234) but it doesn't show the response's body, which in this case contains all the necessary info as shown below:

```
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Release",
      "code": "invalid",
      "field": "target_commitish"
    }
  ],
  "documentation_url": "https://docs.github.com/rest/releases/releases#create-a-release"
}
```

relates to #1421

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.8.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.8.0))
