### ISSUE TITLE
[release] Github can not handle large changelogs

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1448]
It looks like GitHub has a limit for release text of 10k chars. Any content beyond that limit will cut. GitHub can handle a few hundred chars beyond the limit but appears to deny content with much larger lengths, resulting in release failure. 

Add a check before releasing (and not during changelog generation) for the content's length. Fail if length is greater than 10k chars. 

Also, check restrictions for GitLab/Gitea. 

Discovered at https://github.com/INRIA/spoon/issues/5257#issuecomment-1624178667

**Comment by captn3m0** [comment]
Instead of failing, maybe offer a workaround to attach the complete notes as RELEASE.md (and cutting off to 10k characters for the actual notes).

I've found that with generated release notes, a failing release is much harder to fix.

**Comment by aalmiray** [comment]
Following your suggestion, trimmed changelog added as release body while full changelog added as release asset named `RELEASE.md`.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.8.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.8.0))
