### ISSUE TITLE
[core] Files glob does not find any files

### ISSUE THREAD

**Issue by gotson** [jreleaser/jreleaser#1466]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Here is a sample config:

```kotlin
  files {
    glob {
      pattern.set("./output/release/*.*")
    }
  }
```

I also tried `output/release/*` and `output/release/**` without success.

Here is the listing of the above folder from the root of the project:

```
> ls -l ./output/release/ 
total 2165968
-rw-r--r--@ 1 groebroeck  staff   1.2K Aug 11 17:05 InRelease
-rw-r--r--@ 1 groebroeck  staff   600B Aug 11 17:05 Packages
-rw-r--r--@ 1 groebroeck  staff   476B Aug 11 17:05 Packages.xz
-rw-r--r--@ 1 groebroeck  staff   942B Aug 11 17:05 Release
-rw-r--r--@ 1 groebroeck  staff   1.2K Aug 14 14:33 appcast-aarch64.rss
-rw-r--r--@ 1 groebroeck  staff   1.2K Aug 14 14:33 appcast-amd64.rss
-rw-r--r--@ 1 groebroeck  staff   168M Aug 11 17:05 gauthier-roebroeck-komga_1.3.1_amd64.deb
-rw-r--r--@ 1 groebroeck  staff   1.7K Aug 14 14:32 install.ps1
-rw-r--r--@ 1 groebroeck  staff   179M Aug 14 14:33 komga-1.3.1-linux-amd64.tar.gz
-rw-r--r--@ 1 groebroeck  staff   183M Aug 14 14:33 komga-1.3.1-mac-aarch64.zip
-rw-r--r--@ 1 groebroeck  staff   175M Aug 14 14:33 komga-1.3.1-mac-amd64.zip
-rw-r--r--@ 1 groebroeck  staff   175M Aug 14 14:33 komga-1.3.1-windows-amd64.zip
-rw-r--r--@ 1 groebroeck  staff   177M Aug 14 10:35 komga-1.3.1.x64.msix
-rw-r--r--@ 1 groebroeck  staff   4.0K Aug 14 14:32 komga.appinstaller
-rw-r--r--@ 1 groebroeck  staff   1.3K Aug 14 14:32 komga.crt
-rw-r--r--@ 1 groebroeck  staff   697K Aug 14 10:35 komga.exe
-rw-r--r--@ 1 groebroeck  staff   463B Aug 14 14:33 metadata.properties
```

1. Configure a glob in the files block
2. Run jreleaserChecksum
3. no checksums are created for the files in the glob

### Expected Behaviour

Files should be found and checksumed

### Actual Behaviour

Files not checksumed

### Environment Information

- **Operating System**: macOS 13.5
- **JReleaser Version:** 1.7.0
- **JDK Version:** openjdk version "17.0.3" 2022-04-19

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

[trace.log](https://github.com/jreleaser/jreleaser/files/12332228/trace.log)

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.8.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.8.0))
