### ISSUE TITLE
[signing] Add an option for signing individual checksum files

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#147]
Given #146, there should be a way to specify if individual checksum files should be signed or not.

**Comment by aalmiray** [comment]
I don't think this is needed given that all checksums are collected in a single file, and that file is already signed.

**Comment by haydenbaker** [comment]
I think this is a valid use case. I'd also say if 'individual checksums' is enabled, then the grouped checksums file shouldn't be written. Just my 2c.
