### ISSUE TITLE
[changelog] Release notes preambule

### ISSUE THREAD

**Issue by gotson** [jreleaser/jreleaser#1485]
**Is your feature request related to a problem? Please describe.**
Release notes are not always solely composed of a generated changelog, but sometimes also contain text that explains what the release is about and give some context.

At the moment JReleaser does a great job at generating the release notes (i use Github) from the changelog, but if i need to add some text, i need to go back to the release after it was created, and add the text myself.

There are 2 problems with this approach:
1. timing. If i don't edit the release when it gets created, some people will see the release notes without the text i want to add.
2. Multiple channels. I only publish to Github, but that also creates a discussion on Github discussions. Potentially if someone uses more announcers, it would create more places where you would want to edit the generated posts to add custom text.

**Describe the solution you'd like**
I would like to be able to specify some text that would be provided as an input of JReleaser, either in a file or in an environment variable. JReleaser would then incorporate this text when generating the release notes, through the existing template engine.

**Describe alternatives you've considered**
Nothing apart from editing the release notes manually.

**Comment by aalmiray** [comment]
If I understood correctly this is already possible by supplying an external template. This is how JReleaser does it for its own releases:

https://github.com/jreleaser/jreleaser/blob/1a00ae84a72565f024315d1c367659cde1d652e0/jreleaser.yml#L68

https://github.com/jreleaser/jreleaser/blob/main/src/jreleaser/changelog.tpl

**Comment by gotson** [comment]
How would you inject a dynamic string or file in there if I may ask?

**Comment by aalmiray** [comment]
You could use an env var template such as `{{ Env.DYN_STRING}}`

**Comment by gotson** [comment]
> You could use an env var template such as `{{ Env.DYN_STRING}}`

Thanks. Since Environment variables don't support multi-line, i tried using this:

`{{#f_file_read}}{{basedir}}/build/release_notes.md{{/f_file_read}}`

However if the file doesn't exist, i get this error: 

```
Execution failed for task ':jreleaserChangelog'.
> Function failure @[bf4b8f52-fd56-451d-afd6-51cdf4348a74:2]
...
Caused by: java.nio.file.NoSuchFileException: /Users/groebroeck/Development/komga/build/release_notes.md
```

If the environment variable doesn't exist, it doesn't error out and just ignore it.

Would you have some recommendations on how to handle this case ?

**Comment by aalmiray** [comment]
I think we may need a `f_file_exists` template function 😅

**Comment by gotson** [comment]
> I think we may need a `f_file_exists` template function 😅

I think it would be a good addition indeed, and solve the problem nicely 👍🏻

**Comment by aalmiray** [comment]
We may need another function to take content as is, that way we could support dyn strings with multiline content.

**Comment by gotson** [comment]
> We may need another function to take content as is, that way we could support dyn strings with multiline content.

From what I can see the limitation is with the shell, not jreleaser.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.9.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.9.0))

**Comment by gotson** [comment]
@aalmiray i don't quite understand how to combine both `f_file_exists` and `f_file_read`. Would you be able to help me ?

I want to add `{{basedir}}/release_notes/release_notes.md` but only if it exists.

`{{#f_file_exists}}{{basedir}}/release_notes/release_notes.md{{/f_file_exists}}` prints `true` or `false`, but i don't understand how to combine it with `{{#f_file_read}}{{basedir}}/release_notes/release_notes.md{{/f_file_read}}`

**Comment by aalmiray** [comment]
Right. I thought for a moment that there would be a way to combine both functions but it seems it's not possible. There may be the need of another function that performs what you need, `f_file_read_if_exists`.

**Comment by gotson** [comment]
For what it's worth, and because I'm using the gradle kotlin dsl, I've done the check in Kotlin and modified the `content` from there. But that would not work with the yml for instance.
