### ISSUE TITLE
[build] Flakiness in JSON assertion test 

### ISSUE THREAD

**Issue by kavvya97** [jreleaser/jreleaser#1527]
The following tests can be flaky/non-determinisitic in the module **jreleaser-linkedin-java-sdk**
`org.jreleaser.sdk.linkedin.LinkedinSdkTest.testMessageWithExplicitOwner`
`org.jreleaser.sdk.linkedin.LinkedinSdkTest.testMessageWithImplicitOwner`

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem (link to git repository is ideal)
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1.  Build the project using `./gradlew build`
2. Run the test using `./gradlew --info :jreleaser-linkedin-java-sdk:test --tests org.jreleaser.sdk.linkedin.LinkedinSdkTest.testMessageWithExplicitOwner`
3. Run the [Nondex](https://github.com/TestingResearchIllinois/nondex) Tool for the test. Nondex is a tool utilized for detecting flakiness in the tests. When running this command, the test fails
 `./gradlew --info :jreleaser-linkedin-java-sdk:nondexTest --tests org.jreleaser.sdk.linkedin.LinkedinSdkTest.testMessageWithExplicitOwner`

### Expected Behaviour

The tests are expected to pass and should not provide non-deterministic results for every run

### Actual Behaviour

The tests fail with the below error when performing the JSON comparision
```
com.github.tomakehurst.wiremock.client.VerificationException: No requests exactly matched. Most similar request was:
expected:
    POST
    /shares

    Content-Type: application/json
    Accept: */*

    "owner" : "urn:li:person:324_kGGaLE",
    "subject" : "App 1.0.0 released",
    "text" : {
        "text" : "App 1.0.0 has been released"
    }

but was:
    POST
    /shares

    Content-Type: application/json
    Accept: */*

    {
        "text" : {
            "text" : "App 1.0.0 has been released"
        },
        "owner" : "urn:li:person:324_kGGaLE",
        "subject" : "App 1.0.0 released"
    }
```

### Environment Information

- **Operating System**: Linux
- **JDK Version:** 17.0.8.1

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.10.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.10.0))
