### ISSUE TITLE
[jdks] Add an outputFilename option

### ISSUE THREAD

**Issue by charphi** [jreleaser/jreleaser#1595]
**Is your feature request related to a problem? Please describe.**
I'm using [`jdks:setup-disco`](https://jreleaser.org/guide/latest/tools/jdks-maven.html#_jdkssetup_disco) to download a JDK and it works fine except that I don't know the file name of the JDK before and after downloading it. I have to list files in `outputDirectory` to get the name.

**Describe the solution you'd like**
Add an option such as `outputFilename` to be able to easily handle JDK files after downloading them.

**Describe alternatives you've considered**
I currently list all files in `outputDirectory` and get the first one with an Ant task.  
See https://github.com/nbbrd/jdemetra-app-snapshot/blob/c597ff5ac01a6eaedabfdaa3786631feb0c863ae/pom.xml#L310

**Additional context**
My end goal is to download a JDK without unpacking it and merge its content to another zip file so I can preserve the zip entries permissions on all platforms.

**Comment by aalmiray** [comment]
If I understood correctly, you'd like to define the filename of a downloaded package, as well as just downloading (and verifying) said package but skip unpacking, right? The latter is already supported via the `jdks.setup.unpack` property or `<unpack>` configuration property, which is set to `true` by default.

Additionally, the plugin could output the target location/filename of a JDK before downloading.

**Comment by charphi** [comment]
Thanks; that's exactly what I need.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.11.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.11.0))
