### ISSUE TITLE
[announce] Links in Bluesky are not rendered correctly

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1611]
Follow up to https://github.com/jreleaser/jreleaser/issues/1525

JReleaser 1.11.0 rendered links without format

https://bsky.app/profile/jreleaser.bsky.social/post/3kmkmrzw56h24

![jreleaser-bluesky](https://github.com/jreleaser/jreleaser/assets/13969/ad451000-bfca-4885-8a46-82476570096c)

**Comment by TomCools** [comment]
Apparently the Markdown support through the API was not permanently supported and the official way to do it now is to add facets: https://docs.bsky.app/docs/advanced-guides/post-richtext. 

I can pick this up if you have no other takers @aalmiray.

**Comment by aalmiray** [comment]
Go ahead if you have a fix. However, @matheuspaes also wanted to have a stab at it as well

**Comment by TomCools** [comment]
In that case, I'll already list what I think needs to be done to help him tackle this. 

- BlueskyAnnouncer: Remove the Markdown transformation, it is no longer needed.

- CreateTextRecordRequest: expand this DTO to also provide the "facets" as fields. Documentation of the API is here: https://docs.bsky.app/docs/advanced-guides/post-richtext

- Create some utility to take the generated string and find the facets inside it. (following link lists all accepted facet types in Bluesky atm https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/richtext/facet.json). The most important one atm is _app.bsky.richtext.facet#link_ but I would expect new issues in the future if the other ones aren't supported as well.

Note: Make sure to test the new functionality with emojis in the message... I have noticed some weird behavior related to encoding in the past.

If you need any assistance @matheuspaes, ping me and I am more than willing to jump on a call and guide you through it a bit.

**Comment by TomCools** [comment]
@matheuspaesp how is it working out? Need anymore assistance?
