### ISSUE TITLE
[deploy] Support matching stagingProfileId by pattern

### ISSUE THREAD

**Issue by cstamas** [jreleaser/jreleaser#1648]
Current `org.jreleaser.sdk.nexus2.Nexus2` works with Maven Central just fine, but only due MC specifics.

In general, Nx2 staging profile matching can (and usually is) "tweaked" by Nx2 admins. On MC the profiles are in 1:1 match to top level groupIds one can publish, but many forges are not doing this, instead, they "match" profiles by Repository Targets.

Also, Nx2 offers endpoint to perform the match for you:
https://repository.apache.org/nexus-staging-plugin/default/docs/path__staging_profile_evaluate.html

What happens in this method works ONLY for MC as it is set up in specific way, as it has one profile for one Top Level Group:
https://github.com/jreleaser/jreleaser/blob/main/sdks/jreleaser-nexus2-java-sdk/src/main/java/org/jreleaser/sdk/nexus2/Nexus2.java#L126

Instead, the API above should be used to "match" profile and used server side matched profile.

**Comment by aalmiray** [comment]
Looks like the `profile_evaluate` requires a full GAV which we may not necessarily be able to infer given that there may be multiple staged artifacts and none may match artifactId to project name. That is, there's no way to single out a given artifactId.

**Comment by cstamas** [comment]
I think in 99% of cases top level module (just like jreleaser maven plugin setup requires) should suffice, no?

**Comment by cstamas** [comment]
Also, it could be `G:whatever:whatever` as in 99% of cases admins focus on groupId only.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.13.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.13.0))
