### ISSUE TITLE
[gitlab] Release fails if Project Fork exist

### ISSUE THREAD

**Issue by DennisRippinger** [jreleaser/jreleaser#166]
### Background 
My company uses an internal GitLab instance, and we are working on a new project, which has the same name as an already existing one that we are replacing. I also have a fork of the original one, which I use to propose MRs to the maintaining team. Hence, my account sees three repositories with the same name.

### Error
Under these circumstances, if I use the CLI approach to create a release, I get a RestAPIException [from Feign](https://github.com/jreleaser/jreleaser/blob/main/sdks/java-sdk-commons/src/main/java/org/jreleaser/sdk/commons/ClientUtils.java#L81). 

My understanding of what has happened: Since GitLabs API requires using the unique project IDs for a call, JReleaser obtains the Project by searching for a project with the `release.gitlab.name` value. Since my account sees three of these, it fetches the wrong one. 

https://github.com/jreleaser/jreleaser/blob/65b0e520d3bcc6c129e725ae42d65a1bfa6b55aa/sdks/gitlab-java-sdk/src/main/java/org/jreleaser/sdk/gitlab/Gitlab.java#L105-L117

It now uses the wrong project id, and since the desired branch does not exist (master vs. main) GitLab answers with a 400. 

### Environment Information

- **Operating System**:  Mac
- **JReleaser Version:** v0.3
- **JDK Version:** The Homebrew provided one, I believe. 

### Ideas:
- Add a config parameter for GitLab releases to define the project ID explicitly.
- Possibly, this would allow to not rely on personal Tokens but use project-specific ones. Teams could store this Token value in a standard secure enclave  (direnv to a secure, shared team folder, for instance) such that each team member can create a release without providing an additional token. The technical user behind a project token is not allowed to query the getProject API.
- Build something that catches the RestAPIException and allows to handle this error gracefully.

**Comment by aalmiray** [comment]
Adding a field named `projectId` or `identifier` would be the way to go IMHO.

 - [ ] add field to `org.jreleaser.model.Gitlab` (`:jreleaser-model`).
 - [ ] add field to `org.jreleaser.maven.plugin.Gitlab` (`:jreleleaser-maven-plugin`).
 - [ ] map the field in `org.jreleaser.maven.plugin.internal.JReleaserModelConverter` (`:jreleleaser-maven-plugin`).
 - [ ] add field to `org.jreleaser.gradle.plugin.dsl.Gitlab` (`:jreleleaser-gradle-plugin`).
 - [ ] add field to `org.jreleaser.gradle.plugin.internal.dsl.GitlabImpl` (`:jreleleaser-gradle-plugin`).
 - [ ] update `:gitlab-java-sdk` with new behavior.
