### ISSUE TITLE
[deploy] Improve bundle zip file name to include project name

### ISSUE THREAD

**Issue by vkn** [jreleaser/jreleaser#1661]
Jreleaser creates a bundle zip file for maven central named as _namespace + version + "-bundle.zip"_. It would be nice to include the project name as well.

Without the project name, it is hard to see which archive belongs to which project in [sonatype deployments overview](https://central.sonatype.com/publishing/deployments)

The fix should add ` "-" + context.getModel().getProject().getResolvedName() +` in [MavenCentralMavenDeployer.java](https://github.com/jreleaser/jreleaser/blob/7cfd4f4f0026db6bfcc135855d8af41fd4ea2e44/sdks/jreleaser-mavencentral-java-sdk/src/main/java/org/jreleaser/sdk/mavencentral/MavenCentralMavenDeployer.java#L174), I think

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.13.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.13.0))
