### ISSUE TITLE
[assemble] Allow platform specific Java options to be set in javaArchive assembler

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1670]
**Is your feature request related to a problem? Please describe.**
Defining options that are platform specific such as `-DAPP_HOME=${KEY}/app` (linux/mac) or `-DAPP_HOME=%KEY%/app` (windows) requires custom formatting of key names

**Describe the solution you'd like**
An option to define platform specific Java options.

**Describe alternatives you've considered**
Custom templates must be used instead.

cc: @bmarwell

**Comment by bmarwell** [comment]
Thanks! 👍🏻 Will try tomorrow

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.13.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.13.0))
