### ISSUE TITLE
[core] Make `java.groupId` settable using env vars or sys props

### ISSUE THREAD

**Issue by gastaldi** [jreleaser/jreleaser#1709]
> My use case is a bit different: I have a `quarkiverse-release` repository with a jreleaser.yml file used to push to Maven Central. Given that any project in the same org can invoke this workflow, is it possible to set the project groupId dynamically?  

Not at the moment but could be added as a feature. All secret values may be set using env vars or sys props. Only a few non secret values may be set in the same way. `java.groupId` is not one of them as of the latest release.

_Originally posted by @aalmiray in https://github.com/jreleaser/jreleaser/discussions/1708#discussioncomment-10479961_

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.14.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.14.0))
