### ISSUE TITLE
[deploy] Gradle generated POMs cannot be deployed to Maven Central

### ISSUE THREAD

**Issue by ascheman** [jreleaser/jreleaser#1735]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

- Check out [HSC]https://github.com/aim42/htmlSanityCheck
- Switch to the develop branch
- Make sure the latest JReleaser version (0.14.0) is configured in `gradle/libs.versions.toml` (I will fall back to 0.13.1 soon)
- Build the project: `./gradlew check integrationTest`
- Follow some pre-requisites as described in the [development docs](https://hsc.aim42.org/development/publishing.html#_prerequisites) (I think the plugin will never reach the point where it uploads artifacts to Maven Central with this bug, so you can ignore MC settings).
- Deploy (or try to) to Maven Central: `./gradlew jreleaserDeploy -PenableSigning=true` 

### Expected Behaviour

Uploading to MC runs smoothly

### Actual Behaviour

Instead I encounter the following error:

```
[DEBUG]     [mavenCentral] Verifying /.../htmlSanityCheck/build/maven-repo/org/aim42/htmlSanityCheck/org.aim42.htmlSanityCheck.gradle.plugin/2.0.0-rc1/org.aim42.htmlSanityCheck.gradle.plugin-2.0.0-rc1.pom
[DEBUG]     [mavenCentral] org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[DEBUG]     [mavenCentral] [ERROR] Invalid artifact repository: Cannot invoke "org.apache.maven.artifact.repository.ArtifactRepositoryPolicy.isEnabled()" because "policy" is null @ 
```

### Environment Information

- **Operating System**: macOS (latest)
- **JReleaser Version:** 0.14.0
- **JDK Version:** 17

Full trace.log sent to @aalmiray by private communication.

**Comment by ascheman** [comment]
Perhaps it is a problem of `pomchecker`? Using the CLI version 1.12.0 runs into the very same problem, while 1.13.0 doesn't. Then it would be great if the (path provided) pomchcker CLI would be used.

**Comment by aalmiray** [comment]
This may be an issue on Pomchecker, not JReleaser as witnessed in the stacktrace found in the trace log

```

[DEBUG]     [mavenCentral] Verifying /Users/ascheman/wrk/aim42/htmlSanityCheck/build/maven-repo/org/aim42/htmlSanityCheck/org.aim42.htmlSanityCheck.gradle.plugin/2.0.0-rc1/org.aim42.htmlSanityCheck.gradle.plugin-2.0.0-rc1.pom
[DEBUG]     [mavenCentral] org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[DEBUG]     [mavenCentral] [ERROR] Invalid artifact repository: Cannot invoke "org.apache.maven.artifact.repository.ArtifactRepositoryPolicy.isEnabled()" because "policy" is null @ 
[DEBUG]     [mavenCentral] 
[ERROR]     [mavenCentral] java.lang.IllegalStateException: org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR]     [mavenCentral] [ERROR] Invalid artifact repository: Cannot invoke "org.apache.maven.artifact.repository.ArtifactRepositoryPolicy.isEnabled()" because "policy" is null @ 
[ERROR]     [mavenCentral] 
[ERROR]     [mavenCentral] 	at org.kordamp.maven.checker.cli.internal.PomParser.createMavenProject(PomParser.java:102)
[ERROR]     [mavenCentral] 	at org.kordamp.maven.checker.cli.internal.PomParser.createMavenProject(PomParser.java:74)
[ERROR]     [mavenCentral] 	at org.kordamp.maven.checker.cli.CheckMavenCentral.execute(CheckMavenCentral.java:61)
[ERROR]     [mavenCentral] 	at org.kordamp.maven.checker.cli.AbstractCommand.call(AbstractCommand.java:102)
[ERROR]     [mavenCentral] 	at org.kordamp.maven.checker.cli.CheckMavenCentral.call(CheckMavenCentral.java:30)
[ERROR]     [mavenCentral] 	at org.kordamp.maven.checker.cli.AbstractCommand.call(AbstractCommand.java:34)
```

Please refile this error at pomchecker's repo. And include a copy of the generated pom file. Thank you.

**Comment by ascheman** [comment]
As written in Slack, I already found out that this is a problem which occurs only with PomChecker 1.12.0, but nor with 1.11.0 (which is part of JReleaser 0.14.0) neither with PomChecker 1.13.0. I executed both on the Command Line. So perhaps a bugfix release (0.14.1) of JReleaser with PomChecker 1.13.0 could help.

**Comment by aalmiray** [comment]
Pomchecker's version is decoupled from JReleaser's. It can be configured explicitly in the DSL, there's no need for a fix release at the moment. 

However, the default version will be updated for the next release.

**Comment by aalmiray** [comment]
Pomchecker `1.13.0` is already configured as default for the next JReleaser release

https://github.com/jreleaser/jreleaser/blob/931cd1b9996953cd047fddb38e89f9ea0e9982e3/gradle.properties#L98
