### ISSUE TITLE
[plugin] gradle plugin configureModel() should be called just before task execution

### ISSUE THREAD

**Issue by dreamershl** [jreleaser/jreleaser#1755]
**Is your feature request related to a problem? Please describe.**
JReleaserProjectConfigurer::configure() will register tasks with the captured JReleaserModel variable. This will cause the project won't be able to be re-configured in the "afterEvaluate" conditionally 

**Describe the solution you'd like**
All tasks should directly get the "JReleaserModel" within the "execute()"

**Describe alternatives you've considered**
N.A

**Additional context**
N.A

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.16.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.16.0))
