### ISSUE TITLE
[deploy] [mavenCentral] Key XXX was NOT found as published

### ISSUE THREAD

**Issue by fprochazka** [jreleaser/jreleaser#1769]
### Steps to Reproduce

1. create a GPG key locally 
2. publish it 
3. observe the JReleaser claim that it was not published 

### Example

The key was created locally with `gpg --gen-key`, then I've used `gpg --edit-key E8457D2A038F2D3DAA2994120FDC1B69A9BFA044` to extend its expiration 

```
$ gpg --list-keys bot@framefork.org 
pub   rsa3072 2024-11-12 [SC] [expires: 2034-11-10]
      E8457D2A038F2D3DAA2994120FDC1B69A9BFA044
uid           [ultimate] Framefork BOT <bot@framefork.org>
sub   rsa3072 2024-11-12 [E] [expires: 2034-11-10]
```

The key was published to 

* [keyserver.ubuntu.com](https://keyserver.ubuntu.com/pks/lookup?search=E8457D2A038F2D3DAA2994120FDC1B69A9BFA044&fingerprint=on&op=index)
* [keys.openpgp.org](https://keys.openpgp.org/search?q=E8457D2A038F2D3DAA2994120FDC1B69A9BFA044)

Then the key was exported 

```
gpg --output private.asc --armor --export-secret-keys --export-options export-backup
gpg --output public.pgp --armor --export E8457D2A038F2D3DAA2994120FDC1B69A9BFA044
```

Which seems to have been at least somewhat correct, because JReleaser is able to use the key to generate the signatures

https://github.com/framefork/typed-ids/actions/runs/11974523016/job/33385783632

```
[INFO]  Deploying Maven artifacts
[INFO]    [maven] Deploying all staged artifacts
[INFO]      [mavenCentral] Deploying to sonatype
[INFO]      [mavenCentral] Verifying prerequisites
[INFO]      [mavenCentral] Verifying POMs
[INFO]      [mavenCentral] Signing key FDC1B69A9BFA044 expires at 2034-11-10T15:41:28
[INFO]      [mavenCentral] Checking if key FDC1B69A9BFA044 has been published
[WARN]      [mavenCentral] Key FDC1B69A9BFA044 was NOT found as published
```

However, it seems that JReleaser checks for the key via its shortened fingerprint `FDC1B69A9BFA044`, which indeed gives no result 

* [keyserver.ubuntu.com](https://keyserver.ubuntu.com/pks/lookup?search=FDC1B69A9BFA044&fingerprint=on&op=index)
* [keys.openpgp.org](https://keys.openpgp.org/search?q=FDC1B69A9BFA044)

### Expected behavior 

I would expect the JReleaser to search for the full key fingerprint, so that the keyservers find the correct key.

### Environment Information

- **Operating System**: Ubuntu 22.04.5
- **JReleaser Version:** 1.15.0
- **JDK Version:** Java_Temurin-Hotspot_jdk/21.0.5-11/x64

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.16.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.16.0))
