### ISSUE TITLE
[core] Validate YAML config files

### ISSUE THREAD

**Issue by maxandersen** [jreleaser/jreleaser#184]
if your config.yaml have parse errors jreleaser does not let you know.

i had to use yamllint to realize I had a badly formatted multistring.

instead jreleaser just complained about missing values which I was sure I specified correctly ...until I used yamllint :)

**Comment by aalmiray** [comment]
I would had expected Jackson to raise a warning or fail instead of failing silently.
Could you share the bad format you had in place?
