### ISSUE TITLE
Support Winget as packager

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#185]
https://devblogs.microsoft.com/commandline/windows-package-manager-1-0/

**Comment by aalmiray** [comment]
Support for standalone apps (zips) is coming in Winget 1.3 https://github.com/microsoft/winget-cli/issues/182

**Comment by russellbanks** [comment]
> Support for standalone apps (zips) is coming in Winget 1.3 [microsoft/winget-cli#182](https://github.com/microsoft/winget-cli/issues/182) [microsoft/winget-cli#140](https://github.com/microsoft/winget-cli/issues/140)

Standalone apps will be supported in [Winget 1.3](https://github.com/microsoft/winget-cli/releases/tag/v1.3.1872), but the installation of .zip files will be supported in [Winget 1.4](https://github.com/microsoft/winget-cli/releases/tag/v1.4.2011-preview).

**Comment by aalmiray** [comment]
[Winget 1.4 ](https://github.com/microsoft/winget-cli/releases/tag/v1.4.10173)is now available yet there's a note found in the release

 > Note: The [Windows Package Manager Community Repository](https://github.com/microsoft/winget-pkgs) does not accept zip applications. They will not be accepted until after 1.4 is Generally Available and has been rolled out to the majority of Windows systems via the automatic upgrade from the Microsoft Store. Users may test with local manifests.

**Comment by aalmiray** [comment]
solving for `NATIVE_PACKAGE` at the moment. Will tackle `.zip` artifacts later.

**Comment by aalmiray** [comment]
@sualeh please have a look. Manifest templates were modeled after SchemaChrawler found at https://github.com/microsoft/winget-pkgs/tree/71201cbe5797dda84edb7204106d555cb1e3fb5b/manifests/s/schemacrawler/schemacrawler/16.19.7

**Comment by aalmiray** [comment]
Soon switching default installer type from `MSI` to `WIX`. Also, support `.exe` extension besides `.msi`.

**Comment by sualeh** [comment]
@aalmiray When is 1.5.0 planned for release?

**Comment by aalmiray** [comment]
@sualeh earliest it could go is Feb 26th (Sunday), currently scheduled for Feb 28th (Tuesday)

**Comment by aalmiray** [comment]
Released in v1.5.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.5.0

**Comment by russellbanks** [comment]
For releasing, could JPackager integrate with [Komac](https://github.com/russellbanks/Komac) or [WinGet Releaser](https://github.com/vedantmgoyal2009/winget-releaser)?

**Comment by aalmiray** [comment]
At first glance it looks to me the intersection between JReleaser and Komac is generating Winget manifests. Next, Winget Releaser continues by pushing manifest to a particular repository and opening PRs if not mistake. JReleaser performs the former but not the latter (yet) as it also would have to handle MRs on GitLab and PRs on Gitea.

That being said it feels to me that Komac and Winget Releaser are a good combination already, there's not much that JReleaser could do to enhance the experience other than replacing those two tools IMHO if additional package manager support were to be desired.

**Comment by russellbanks** [comment]
Komac does all of the process - WinGet Releaser just gets the URLs from a release and provides that to Komac (along with a token, etc). I'm a little confused about what you mean with PRs on GitLab and Gitea as packages get accepted to WinGet by PRs to winget-pkgs, which is on GitHub.

**Comment by aalmiray** [comment]
The way I've currently setup publishing winget manifests for JReleaser itself is via an intermediate repository (https://github.com/jreleaser/jreleaser-winget) that keeps all of its manifests separate. This repository is updated on every release. The repository has a GH workflow that creates a branch on `winget-pkgs`.

One could replicate this behavior by hosting a Repository on Gitlab. The intermediate repository would eventually have to send a PR to winget-pkgs on GitHub.

Alternatively, JReleaser could push to both `jreleaser-winget` and `winget-pkgs` in such way that copies of the manifests are kept in the `jreleaser-winget`, and a PR with the new bits is sent to `winget-pkgs`. Have to think how to express that in the DSL, as while the current setup is fine with my tastes I'm sure some would prefer to skip the intermediate repository altogether and push directly to `winget-pkgs`.
