### ISSUE TITLE
[github] Create a discussion matching a release

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#186]
https://docs.github.com/en/rest/reference/repos#create-a-release

Requires setting `discussion_category_name`

**Comment by aalmiray** [comment]
Blocked by upstream https://github.com/hub4j/github-api/issues/1171

**Comment by jlengrand** [comment]
Not blocked any more ! :)

**Comment by aalmiray** [comment]
Thanks! We just have to wait for the next release to try it out.
However looking at the release notes for `1.130` I see that https://github.com/hub4j/github-api/pull/1083 has been reverted. IIRC this issue impacted us because we run on JDK8 and PATCH is not supported unless reflection tricks are used, and it's those reflection tricks the ones that caused a warning with Java 9 up to 5, see https://github.com/hub4j/github-api/issues/754

It's likely that hub4j will fail with Java 17 due to reflective access being strictly forbidden.

**Comment by jlengrand** [comment]
We're back to https://github.com/jreleaser/jreleaser/issues/208 it seems :D
