### ISSUE TITLE
Support Github Discussions for non organization repositories

### ISSUE THREAD

**Issue by jlengrand** [jreleaser/jreleaser#208]
**Is your feature request related to a problem? Please describe.**

As it stands now, the REST API from GitHub only supports organization repositories.

**Describe the solution you'd like**

This is minor but this confused me at first. 
For the short term I've proposed a one liner addition to the documentation : https://github.com/jreleaser/jreleaser.github.io/pull/8

In the longer run, it seems like looking into [the GraphQL API](https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions#creatediscussion) could be a solution.

Not sure it is worth fixing though.

**Describe alternatives you've considered**
Nothing, warning the user is probably enough.

**Additional context**

**Comment by jlengrand** [comment]
In case this is not clear. The short term solution is definitely enough for me to close this issue :)

**Comment by aalmiray** [comment]
Agreed. I was surprised to find that the REST API only provides access to Discussions through organizations and teams. 

It's also possible to create a discussion based on a release, which gets a copy of the release's body, but if you'd want different content then I'm afraid it's not possible, yet. I'll keep looking for options.

**Comment by jlengrand** [comment]
Right, I'm guessing you're referring to https://github.com/jreleaser/jreleaser/issues/186 here.

**Comment by aalmiray** [comment]
That's correct. One option I'm considering is to stop using hub4j (which provides access to most of GitHub's API) and craft a smaller version of the API as it's done for Gitea/GitLab already.

**Comment by jlengrand** [comment]
I'm looking into the issue a bit myself right now on hub4j's side. Having a thinner API layer would indeed have some nice additional goodies (GitHub seems to be pushing GraphQL hard you could get more functionalities that way). It's more work though.

**Comment by jlengrand** [comment]
Not really satisfied, but https://github.com/hub4j/github-api/pull/1180

**Comment by aalmiray** [comment]
Awesome. Thanks!

**Comment by aalmiray** [comment]
https://github.com/jreleaser/jreleaser/issues/186 has been fixed, which links a release with a discussion topic.
The GitHub Discussions announcer was originally conceived to perform this task. Technically speaking it could be removed though it also allows opening a "release" discussion with additional content, not just a copy of the release body.

**Comment by aalmiray** [comment]
I think the current features are enough. The discussion announcer works with teams, while the release can post to a discussion category regardless of teams or not.
