### ISSUE TITLE
[maven] Documentation for Distributions is missing the name attribute 

### ISSUE THREAD

**Issue by jruaux** [jreleaser/jreleaser#228]
Documentation for distributions via Maven does not mention the `name` element.
This does not work:
```
<jreleaser>
  <distributions>
    <app>
      <artifacts>...</artifacts>
    </app>
  </distributions>
</jreleaser>
```

but this does:
```
<jreleaser>
  <distributions>
    <app>
      <name>myapp</name>
      <artifacts>...</artifacts>
    </app>
  </distributions>
</jreleaser>
```

Happy to submit a PR if needed.

**Comment by aalmiray** [comment]
Thanks. I think it's more than a doc issue, rather a missing setter call given that the name of the entity is already given, no need to define it explicitly twice. This applies to <distributions>, <assemble>, and <upload> at the very least. 

I believe the fix should go on the `JReleaserModelConverter` class found in the `jreleaser-maven-plugin` project.
