### ISSUE TITLE
[core] Could not determine git HEAD - when running jreleaser in a submodule

### ISSUE THREAD

**Issue by maxandersen** [jreleaser/jreleaser#244]
trying to jreleaser wiht quarkus cli and hitting this issue:

```
[INFO]  JReleaser 0.4.0
[INFO]  Configuring with jreleaser.yml
[INFO]    - basedir set to /Users/max/code/work/quarkus/quarkus/devtools/cli
[INFO]  Reading configuration
Could not determine git HEAD
repository not found: /Users/max/code/work/quarkus/quarkus/devtools/cli
```

should jreleaser not just look for .git in parent dirs.

**Comment by aalmiray** [comment]
Could you post the stracktrace found in `out/jreleaser/trace.log`? Thanks!

**Comment by aalmiray** [comment]
I found the place where the error is triggered. The expectation is that the `context.basedir` points to the root of the project, where the `.git` directory is also found. If there's not `.git` directory then JReleaser fails immediately.

Now there's a new expectation: JReleaser invoked on a subdirectory of an existing Git repository. 

The tool must keep the current validation in place, I think supporting the new expectation should be done by explicitly setting a configuration flag that allows searching upwards until a `.git` directory is found or not.

**Comment by aalmiray** [comment]
@maxandersen is your repository using git submodules? Because regular submodules (i.e, invoking JReleaser on a normal subdirectory isnide a Git repository) works.

**Comment by maxandersen** [comment]
No. It's quarkusio/quarkus repo. Several hundred maven modules and the cli is one of them. The rest released separately. 

I could kinda see we could put it in root and might do that eventually but just found it like a unnecessary limitation.

**Comment by aalmiray** [comment]
Got it. Is the JReleaser configuration added as CLI or as Maven DSL? I ask given that the Maven plugin can read the `jreleaser.yml` file 😏

**Comment by aalmiray** [comment]
Alright, found it. Given that the standard way to invoke JReleaser is from the root of a project the current fix is to add a new flag `--git-root-search` (`-grs` for short) that enables searching for the git root upwards in the file hierarchy when the current directory is not the root.

@maxandersen would that be acceptable?

**Comment by maxandersen** [comment]
that will work yes; personally i believe it should do that by default but all fine :)

question: which location will the paths in jreleaser.yaml have to be relative to ? the git root or the location of jreleaser.yaml?

**Comment by aalmiray** [comment]
OK. I'll add the flag with explicit mode first. We can revisit if that behavior should become the default later 😏 

The paths inside `jreleaser.yml` are related to the `basedir` value, which by default is set to the directory where `jreleaser.yml` is found. You can change this by passing `--basedir` or `-b` when invoking the CLI.

**Comment by ebullient** [comment]
The flag works. ;)
