### ISSUE TITLE
[package] Scoop distribution does not work with SINGLE_JAR

### ISSUE THREAD

**Issue by maxandersen** [jreleaser/jreleaser#246]
using SINGLE_JAR does not work with scoop despite https://jreleaser.org/guide/latest/distributions/single-jar.html saying otherwise.

it just installs a .jar - no bat file to actually run is put int o path.

**Comment by aalmiray** [comment]
The distribution URL points to a `.jar` file which limits the use of a launcher script as part of the distribution. However it may be possible to define a launcher inline, as shown by https://github.com/lukesampson/scoop-extras/blob/master/bucket/jd-gui.json
