### ISSUE TITLE
Unexpected error when creating release

### ISSUE THREAD

**Issue by charphi** [jreleaser/jreleaser#285]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Maven project with `jreleaser-maven-plugin`
2. Set the following options:
```xml
<configuration>
    <jreleaser>
        <release>
            <github>
                <owner>nbbrd</owner>
                <overwrite>true</overwrite>
                <skipTag>true</skipTag>
                <draft>true</draft>
            </github>
        </release>
    </jreleaser>
</configuration>
```
3. Run the release command: `mvn -B -ntp jreleaser:full-release`

Full example: https://github.com/nbbrd/sandbox 

### Expected Behaviour

The command is executed by a GitHub action on a Tag event.
It should create a new GitHub release from the current Tag (the tag is created elsewhere).

### Actual Behaviour

The release fails with the following message:
```
Error:  Failed to execute goal org.jreleaser:jreleaser-maven-plugin:0.5.0:full-release (default-cli) on project sandbox-parent: Execution default-cli of goal org.jreleaser:jreleaser-maven-plugin:0.5.0:full-release failed: Unexpected error when creating release. org.kohsuke.github.HttpException: {"message":"Validation Failed","errors":[{"resource":"Release","code":"invalid","field":"target_commitish"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-a-release"}: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/nbbrd/sandbox/releases -> [Help 1]
```

### Environment Information

- **Operating System**: latest Ubuntu
- **JReleaser Version:** 0.5.0
- **JDK Version:** 11

**Comment by charphi** [comment]
I've just found a workaround: set the target branch in configuration

```xml
<configuration>
    <jreleaser>
        <release>
            <github>
                <owner>nbbrd</owner>
                <overwrite>true</overwrite>
                <skipTag>true</skipTag>
                <draft>true</draft>
                <branch>master</branch>
            </github>
        </release>
    </jreleaser>
</configuration>
```

**Comment by aalmiray** [comment]
I was about to suggest setting the branch to `master` as the default value is `main`. This being said, JReleaser should had found out the name of the current branch and use it. Looks like the `ModelConfigurer` needs a fix https://github.com/jreleaser/jreleaser/blob/286c04a9328d838b45f58a83943c5eec7cf6af97/core/jreleaser-engine/src/main/java/org/jreleaser/engine/context/ModelConfigurer.java#L168

**Comment by aalmiray** [comment]
Bug confirmed on `0.5.0` but cannot reproduce with `0.6.0-SNAPSHOT` at 8f49c26ba95af709718f7ffe532dc46068a67928.
Appears to be fixed.

**Comment by charphi** [comment]
Ok; thanks
