### ISSUE TITLE
[scoop] Individual checksum and packagers 

### ISSUE THREAD

**Issue by charphi** [jreleaser/jreleaser#287]
Some packagers (at least Scoop) use individual checksum in their script (see `autoupdate.hash.url`).
There is currently no warning nor error if individual checksum is not enabled (disabled by default).

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create any project
2. Add Scoop packager
3. Do not enable individual checksum

### Expected Behaviour

Warn about the possible problem.

### Actual Behaviour

No warning is displayed.

### Environment Information

- **Operating System**: Ubuntu
- **JReleaser Version:** 0.5.0
- **JDK Version:** 11

**Comment by aalmiray** [comment]
JReleaser will now activate individual checksum upload for every matching artifact that will be packaged with Scoop.

**Comment by charphi** [comment]
Thanks!
