### ISSUE TITLE
[docker] Ability to add extra file to a distribution/repo 

### ISSUE THREAD

**Issue by maxandersen** [jreleaser/jreleaser#330]
usecase: trying to configure the docker publisher but I like to add a readme and a action.yml (to make it a github action docker repo). 

I tried adding `src/jreleaser/distributions/jbang/docker/README.tpl` but still only got a dockerfile. 

Is there a way to add additional files for the distributions that updates/modifiies a repo ?

**Comment by maxandersen** [comment]
note, I see there are things like ${docker.templateDirectory}/assembly but they dont seem to support using templates  ?

**Comment by maxandersen** [comment]
also, in case of docker these files are not meant for the image but for the repo.

**Comment by aalmiray** [comment]
Any files placed under `src/jreleaser/distributions/<jbang>/docker/` will be automatically copied to the prepare and package directories found in `out/jreleaser[prepare|package]/distributions/<name>/docker/`. These files are **not** added to the generated image. For example

```
src/
├── jreleaser
│   ├── distributions
│   │   └── app
│   │       └── docker
│   │           ├── README.adoc
│   │           └── README.md.tpl
```

Results in

<img width="726" alt="jreleaser-docker-repository" src="https://user-images.githubusercontent.com/13969/127873561-69e175d6-b251-4c58-a311-31e966db26c7.png">


If `src/jreleaser/distributions/<jbang>/docker/assembly` exists then any files placed there will be added to the generated image.

Templates will be evaluated for all files, which is something I find a bit troublesome specifically with binary files (such as images). Templates should be evaluated only for files ending with `.tpl` IMHO.
