### ISSUE TITLE
OpenJDK15 archives (Linux/OSX/Windows) unpack to same dest folder

### ISSUE THREAD

**Issue by ghubstan** [jreleaser/jreleaser#363]
### Task List

- [x] Steps to reproduce provided
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure `org.jreleaser.jdks` plugin to download, unpack and verify OpenJDK 15 archives for Linux, OSX, Windows.
```
plugins {
    id 'org.jreleaser.jdks' version '0.6.0'
}

...

jdks {
    openJdk15Linux {
        platform = 'linux'
        url = 'https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.2%2B7/OpenJDK15U-jdk_x64_linux_hotspot_15.0.2_7.tar.gz'
        checksum = '94f20ca8ea97773571492e622563883b8869438a015d02df6028180dd9acc24d'
    }
    openJdk15Windows {
        platform = 'windows'
        url = 'https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.2%2B7/OpenJDK15U-jdk_x64_windows_hotspot_15.0.2_7.zip'
        checksum = 'b80dde2b7f8374eff0f1726c1cbdb48fb095fdde21489046d92f7144baff5741'
    }
    openJdk15Osx {
        platform = 'osx'
        url = 'https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.2%2B7/OpenJDK15U-jdk_x64_mac_hotspot_15.0.2_7.tar.gz'
        checksum = 'd358a7ff03905282348c6c80562a4da2e04eb377b60ad2152be4c90f8d580b7f'
    }
}

```
2. Run `setupJDKs` task

### Expected Behaviour

Distributions are unpacked to different destination folder names, and `setupJDKs` completes as it does for zulu distributions.

### Actual Behaviour

Distributions are unpacked to the same destination folder name `jdk-15.0.2+7`, and 2nd unpack task fails (`permission denied`) because destination folder name exists, and contains contents of 1st unpack task.

### Environment Information

- **Operating System**: Linux
- **JReleaser Version:** 0.6.0
- **JDK Version:** OpenJDK 15

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

**Comment by ghubstan** [comment]
I've never used Zulu dists, and didn't know they are OpenJDK builds until after posting this issue.

**Comment by aalmiray** [comment]
JDKs will now be downloaded to a directory matching their name such that the "openJdk15Linux" will be downloaded and expanded to `build/openJdk15Linux/jdk-15.0.2+7`.
