### ISSUE TITLE
[changelog] Tag/Version range for changelog

### ISSUE THREAD

**Issue by andreabettich** [jreleaser/jreleaser#382]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to define a range of tags/versions to find all commits in between to generate the changelog.

**Describe alternatives you've considered**

**Additional context**
We are creating tags for every push to master, but are creating gitlab releases after we have a couple of features/fixes in the master. So our release changelog would consist of multiple tags.

**Comment by aalmiray** [comment]
Would specifying a single tag (the oldest) in the range be sufficient?

Or do you need both first and last tags?

**Comment by andreabettich** [comment]
Wouldn't be the first tag be the `release.gitlab.tagName` or `project.version` in the configuration? Then I would only need to define the tag from which it should start to collect the commits until the tag/version defined in the config already.

**Comment by aalmiray** [comment]
Yes, that is correct, the first tag (start) is already configurable while the second (end) is not at the moment. Just checking if you needed a different start tag.

**Comment by andreabettich** [comment]
I hacked together a draft version of it. Not sure if the naming is good and if I found all the places where it has to be.
