### ISSUE TITLE
[core] support single-jar distributions

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#39]
Allow for single jar (a.k.a executable [uber]jar) to be configured as a distribution.

JAR must be executable (`Main-Class:` manifest attribute) and contain all required dependencies within itself (shaded for example)

- [ ] support brew
- [ ] support docker
- [ ] support jbang
- [ ] support snap

**Comment by charphi** [comment]
What about Scoop.sh? It seems that is it possible (see https://github.com/rivy/scoop.bucket.scoop-main/blob/master/pdfbox.json)
