### ISSUE TITLE
[sign] Support signing via sigstore

### ISSUE THREAD

**Issue by sormuras** [jreleaser/jreleaser#391]
https://www.sigstore.dev

> A new standard for signing, verifying and protecting software - Making sure your software’s what it claims to be.

`cosign --sign-blob ...` and `cosign --verify-blob ...` are the current support modes to sign/verfiy JAR files. Especially the "keyless" mode seems is interesting. See https://martinheinz.dev/blog/56 for details.

**Comment by dlorenc** [comment]
Just saw this issue! I'm a sigstore maintainer and would love to help here. We just did an integration with goreleaser that worked great!

Feel free to reach out on Twitter or over email if you have any questions!

**Comment by aalmiray** [comment]
Thank you for the kind offer! I'm aware of the maven plugin already hosted at the sigstore organization. Perhaps some of that code may be reused in a way. 

JReleaser is a tool that can be invoked in several ways: as a Maven plugin, as a Gradle plugin, as Ant take, or as a CLI. We make it happen by pushing down the required behavior to a single interface that plugins consume. This interface must remain Java 8 compatible for the foreseeable future due to constraints imposed by the consuming plugins (Maven uses Java 8 as a minimum baseline, I believe Gradle as well).

Additionally, we'd prefer to have as few dependencies as possible, skipping Guava or any other Google APIs as a result. 

Ideally, a sigstore impl for Java (sigstore4j?) could be delivered as a library with Java8's URLConnection/HTTPConnection (failing that Apache's HttpClient) and Jackson (for JSON marshalling). Or perhaps the HTTP and JSON layers may be pluggable so that if a consumer would like to use OkHttp, Gson, or something else could do so with minimum configuration from their side.

**Comment by aalmiray** [comment]
@dlorenc how should we proceed with this idea? 😅

**Comment by dlorenc** [comment]
Cc @bobcallaway and @loosebazooka for input! They're much more knowledgeable about the existing Java implementation.

**Comment by loosebazooka** [comment]
I would prefer a simple pass-through to cosign (so the core implementation remains in a single place). The java tooling could just help make that very easy by.
- publishing a multiplatform bundle of cosign to maven central (or some java repository)
- code to handle downloading, extracting and executing cosign

**Comment by loosebazooka** [comment]
> @loosebazooka does that mean issuing a process call to invoke the cosign executable?

Yeah, is that unacceptable?

**Comment by aalmiray** [comment]
Not really, more like a stop gap option IF there were a Java solution in the works. JReleaser does provide integration with externals tools when there are platform specific concerns, such as building snapcraft or chocolatey packages, as you must rely on platform binaries to do so, there are no Java libraries. It also calls to jlink, jpackage, and native-image executables. 

Executing cosign directly is doable with the caveat that consumers must have the executable available before hand, just like snap and choco must be.

**Comment by aalmiray** [comment]
Alternatively, JReleaser *could* download cosign matching the currently executing platform skipping the manual step to setup cosign before hand.

**Comment by loosebazooka** [comment]
> IF there were a Java solution in the works
I think we're trying to figure that out here. There are costs to development with maintaining two or more language implementations of the same code. And there are costs to the user, for example a java user using non-java tooling (but we can aim to make this easy).

If there are no restrictions on subprocess execution, I think we can make the experience of using the cosign binary from java fairly convenient with the right wrapper tooling without rewriting cosign.

> JReleaser could download cosign
I do think the software generating any artifact metadata (provenance/sbom) should know what version of cosign is being used, it's digest, where it came from, etc. It's not clear to me that this is gradle/maven/ant or if it's jreleaser or even someone else. In my mental model, provenance/attestations are generally the domain of the build service (CI), where as an sbom can be generated by the build tooling (gradle/maven). I think there's a lot to think about here and maybe it's beyond the scope of this discussion.

**Comment by aalmiray** [comment]
re: provenance. Would it help if JReleaser had an option (as part of its configuration) that defines which version of cosign should be used in case that it must be downloaded by the tool? One could also specify a checksum to verify that the downloaded binary is correct.

Automatic download should only occur if there's no cosign binary in the system already, or if the existing cosign binary's version does not match the configured one. WDYT?

**Comment by loosebazooka** [comment]
> Automatic download should only occur if there's no cosign binary in the system already, or if the existing cosign binary's version does not match the configured one. WDYT?

Yeah sure, we can build those requirements into the design of the wrapper library. Lemme have a chat with the cosign devs and we can put together a small design.

**Comment by loosebazooka** [comment]
So maybe this is the place to ask. What kind of signing is jreleaser looking for? Blob signing? or Jar signing (via jarsigner)? Or both?

**Comment by aalmiray** [comment]
I think blob signing is the way to go as JReleaser can sing all kind of release assets (JARs, Zips, Tars, text files, etc).

I've done some work for downloading external tools (UPX at the moment) thus I'm pretty sire I can do the same for cosign. I've got a follow up question regarding signing keys. I'm aware of keyless signing but if someone were to prefer explicit keys, where would they publish public keys for anyone else to verify blobs?

Is there a preferred set of servers that can hold cosign public keys?
Or should public keys be part of the release assets?

+@dlorenc

**Comment by aalmiray** [comment]
Almost there. JReleaser can resolve or download cosign, generate a key pair if none are available, sign & verify all blobs, upload public key as release asset.
<img width="645" alt="jreleaser-cosign" src="https://user-images.githubusercontent.com/13969/149421531-d01a0889-5c17-4d2e-b2c7-e3b9e8939bbe.png">

**Comment by aalmiray** [comment]
Keyless signing may be added later.

**Comment by loosebazooka** [comment]
@aalmiray, revisiting this as we got around to writing a java client at github.com/sigstore/sigstore-java. Any idea what support is missing or incompatible with jreleaser -- for instance we use java11 and quite a few libraries.

**Comment by aalmiray** [comment]
Thank you for the update. Java 8 is still our baseline. We hope to move to 11 next year once Maven 4 comes out. 

Also, the use of Google dependencies is a non starter at the moment. We've gone to great lengths to avoid Guava to creep into our dependency graph for example. I know there are teams that are fine with Google dependencies and that's OK, we simply would like to avoid them.

**Comment by loosebazooka** [comment]
Sgtm. That's part of our goal to pare down dependencies. I think we need to find a decent okhttp oauth client first. Is grpc okay though?
