### ISSUE TITLE
[brew] Configuring tap `owner` in brew packager with gradle plugin fails with "Cannot set the value of read-only property"

### ISSUE THREAD

**Issue by itzg** [jreleaser/jreleaser#449]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Using jreleaser gradle plugin version 0.7.0 or 0.8.0, configure a brew tap with an owner specified or clone the repo [itzg/try-jreleaser-brew](https://github.com/itzg/try-jreleaser-brew)

```
    packagers {
        brew {
            active = 'RELEASE'
            tap {
                owner = 'any'
                name = 'homebrew-tap'
            }
        }
    }
```

2. Perform any gradle operation such as `./gradlew build`

### Expected Behaviour

Gradle operation should succeed.

### Actual Behaviour

Every gradle operation reports "BUILD FAILED" with

```
FAILURE: Build failed with an exception.

* Where:
Build file '[redacted]\try-jreleaser-brew\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'try-jreleaser-brew'.
> Cannot set the value of read-only property 'owner' for root project 'try-jreleaser-brew' of type org.gradle.api.Project.
```

Note: using the `scoop` packager with the same bucket owner works fine, such as
```
    packagers {
        scoop {
            active = 'RELEASE'
            bucket {
                owner = 'itzg'
                name = 'scoop-bucket'
            }
        }
```

### Environment Information

- **Operating System**: Windows
- **JReleaser Version:** 0.8.0 and 0.7.0
- **JDK Version:** AdoptOpenJDK 16
- **Gradle Version:** 7.1 and 6.9

> NOTE stacktrace from `[out|build|target]/jreleaser/trace.log` is not available since the build fails early within gradle initialization

**Comment by itzg** [comment]
Possibly related, IntelliJ warns about the `project` block of the `jreleaser` extension:

![image](https://user-images.githubusercontent.com/988985/139538938-fbb17822-0468-49e4-97ad-1ab08c89754b.png)

and does not resolve the `packagers` block:

![image](https://user-images.githubusercontent.com/988985/139538964-11237710-1dd6-40c2-b483-dff536f153b2.png)

**Comment by aalmiray** [comment]
Hmm this could be a gotcha when using the Groovy DSL as the `Closure` type has a read-only property named `owner`. If so we'll have to rename the property in the Gradle DSL so that it no longer collides.

**Comment by itzg** [comment]
Agreed. Both `owner` and unfortunately `project` seem to be sacred identifiers for Groovy. It's still odd that the `owner` within scoop resolves fine.

**Comment by aalmiray** [comment]
Hmm `project` is not sacred to Groovy, it's an identifier defined by the Gradle DSL. IntelliJ gets confused and sees a nested `project` as being the top level one, so really it's the IDE support at fault here, not Gradle nor Groovy.

I would had expected `owner` to fail for everyone, the fact that it works for scoop but not for brew makes me think perhaps I wired up something incorrectly for Brew.

**Comment by aalmiray** [comment]
Actually it seems `scoop` is not working at all either. The whole `packagers` block is ignore, you can tell by running `./gradlew jreleaserConfig` and you'll notice that the `packagers` block is missing and that the `mc-image-helper` distribution (added by default) does not have `scoop` configured as well.

**Comment by aalmiray** [comment]
Digging further, both Gradle `6.9` and `7.0` report

```
> Could not set unknown property 'owner' for object of type org.jreleaser.gradle.plugin.internal.dsl.BrewImpl.
```

While Gradle `7.1` and `7.2` report

```
> Cannot set the value of read-only property 'owner' for root project 'mc-image-helper' of type org.gradle.api.Project.
```

**Comment by aalmiray** [comment]
FWIW you can still set properties on the tap directly, that is

```yaml
jreleaser {
    packagers {
        scoop {
            active = 'ALWAYS'
            bucket {
                owner = 'itzg'
                name = 'scoop-bucket'
            }
        }
        brew {
            active = 'ALWAYS'
            tap.owner = 'itzg'
            tap.name = 'homebrew-tap'
        }
    }
}

**Comment by aalmiray** [comment]
Found it. The problem is caused by a signature clash from the Groovy GDK. Since `2.5.0` there's a method named `tap()` https://docs.groovy-lang.org/latest/html/groovy-jdk/java/lang/Object.html#tap(groovy.lang.Closure) added to the base `java.lang.Object` type. 

This means `brew.tap { }` is routed through the GDK method instead of JReleaser's.

**Comment by itzg** [comment]
Good find! I'm good with using using `tap.owner`, so you're welcome to close this issue.

**Comment by aalmiray** [comment]
I think it's better to rename both the `tap` property and method to `repoTap` so that both options may be used.
