### ISSUE TITLE
[gradle] overwrite property and env variable don't seem to be used by github release step 

### ISSUE THREAD

**Issue by itzg** [jreleaser/jreleaser#454]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Perform a full release at a tagged repo revision like normal
2. Invoke the `jreleaserFullRelease` gradle task again at the same tagged repo revision, but with the two documented ways to overrite the existing Github repo: `JRELEASER_OVERWRITE=true ./gradlew jreleaserFullRelease -Pjreleaser.overwrite=true`

> The step above sets both the environment variable and property to try the two ways documented, such as [here](https://jreleaser.org/guide/latest/configuration/release/github.html) and [here](https://jreleaser.org/guide/latest/configuration/environment.html#_gradle)

### Expected Behaviour

Expected the Github release to get overwritten and proceed even though one already existed.

### Actual Behaviour

Gradle build fails with
```
[ERROR] JReleaser failed after 2.467 s

> Task :jreleaserFullRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jreleaserFullRelease'.
> Unexpected error when creating release
```

Details output shows the following, notice it says "overwrite = false"

```
GitHub release failed because release v1.0.6 already exists. overwrite = false; update = false
```

Stepping through the code while debugging the task execution I noticed that unlike `org.jreleaser.model.GitService#getResolvedToken` there isn't environment variable lookups for any other fields even though the docs say:

```
    # Drops and creates an existing release with matching tag.
    # May define a `JRELEASER_OVERWRITE` environment variable instead.
    # Defaults to `false`.
    #  
    overwrite: true
```

I also noticed that the `AbstractGitService#overwrite` gets initialized with a convention of undefined

https://github.com/jreleaser/jreleaser/blob/00b584f2f8971eaf834b6a68db110fd5a1777216/plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/dsl/AbstractGitService.groovy#L106

### Environment Information

- **Operating System**: WSL2 Ubuntu
- **JReleaser Version:** 0.8.0
- **JDK Version:** 17

[trace.log](https://github.com/jreleaser/jreleaser/files/7449453/trace.log)

**Comment by aalmiray** [comment]
The fault is setting a `false` value by default

https://github.com/jreleaser/jreleaser/blob/96a853731c3345bcdff9010d2520010b6fd12cfa/plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/dsl/AbstractGitService.groovy#L256-L260

This makes validation skip checking for env vars

https://github.com/jreleaser/jreleaser/blob/96a853731c3345bcdff9010d2520010b6fd12cfa/core/jreleaser-model/src/main/java/org/jreleaser/model/validation/GitServiceValidator.java#L117-L124

**Comment by aalmiray** [comment]
I believe `-Pjreleaser.overwrite=true` does not work at all as there are no mappings from Gradle project properties to JReleaser model fields at the moment. The `jreleaserAutoConfigRelease` task exposes command flags such as `--overwrite` but neither `jreleaserRelease` nor `jreleaserFullRelease` expose command flags.

**Comment by itzg** [comment]
Ah, it missed those spots when debugging. I'll set some breakpoints at those spots.

So, can it only be overridden by an environment variable? If so, is `JRELEASER_OVERWRITE` not the correct one?

**Comment by aalmiray** [comment]
Yes, `JRELEASER_OVERWRITE` is the correct setting but I'm afraid that `v0.8.0` short-circuits checking the environment variable because the value of `release.github.overwrite` will always be set before the env var is checked. This is indeed a bug for which you can't get around using env vars in `v0.8.0`, only setting the value of `release.github.overwrite` explicitly.

You may use a project property but you have to define the name and make sure that it resolves to a `boolean` value

```
jreleaser {
    release {
        github {
           overwrite = (project.rootProject.findProperty('geoff.overwrite') ?: false).toBoolean()
        }
    }
}
```

Then invoke as `gradle -Pgeoff.overwrite=true jreleaserFullRelease`

**Comment by itzg** [comment]
Thanks, yep, I was happy to fallback to `overwrite = (project.rootProject.findProperty('geoff.overwrite') ?: false).toBoolean()` but was curious to chase down the "documented" way 😃

You beat me to it, but did want to confirm that I see the env var processing is skipped since the property thinks it is already set since the `getOrElse` happened previous to it
![image](https://user-images.githubusercontent.com/988985/139598168-a1a455c6-806c-41ef-9afc-9f9a69035819.png)
