### ISSUE TITLE
[brew] `JRELEASER_HOMEBREW_${GIT}_TOKEN` doesn't work for alternate token declaration

### ISSUE THREAD

**Issue by itzg** [jreleaser/jreleaser#459]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Declare a github action invoking the gradle jreleaserFullRelease task with[ `JRELEASER_GITHUB_TOKEN` set to the action scoped `GITHUB_TOKEN` secret](https://github.com/itzg/prune-branches/blob/84053fed604701d472a11de0fc005c6e758e2fc0/.github/workflows/publish-release.yml#L34) and [`JRELEASER_HOMEBREW_GITHUB_TOKEN` set to a personal access token](https://github.com/itzg/prune-branches/blob/84053fed604701d472a11de0fc005c6e758e2fc0/.github/workflows/publish-release.yml#L36) declared with repo scope.
2. The build step fails during homebrew publishing, such as [this build](https://github.com/itzg/prune-branches/actions/runs/1403827226) where [the trace log](https://github.com/itzg/prune-branches/suites/4211306885/artifacts/108796528) shows the specific failure point

### Expected Behaviour

Expected homebrew publication to work since [the use of `JRELEASER_HOMEBREW_${GIT}_TOKEN` is documented here](https://jreleaser.org/guide/latest/configuration/packagers/homebrew.html), where `${GIT}` is `GITHUB` in this case.

### Actual Behaviour

Build fails.

While stepping through the build with the debugger, I found that here the service basename is declared as "homebrew-tap" and not just "homebrew"

https://github.com/jreleaser/jreleaser/blob/a38a2caec594af68111f644c7821c61d882d0e5c/core/jreleaser-model/src/main/java/org/jreleaser/model/HomebrewTap.java#L26

So [setting `JRELEASER_HOMEBREW_TAP_GITHUB_TOKEN`](https://github.com/itzg/prune-branches/blob/f9a86375a495a016333af058ae475144398c632c/.github/workflows/publish-release.yml#L36
) worked correctly in [this subsequent github action build](https://github.com/itzg/prune-branches/runs/4061576151?check_suite_focus=true#step:6:55),

### Environment Information

- **Operating System**: Linux
- **JReleaser Version:** 0.8.0
- **JDK Version:** 17

**Comment by aalmiray** [comment]
I'm afraid Chocolatey and JBang will face the same problem

https://github.com/jreleaser/jreleaser/blob/32cb7edda1af1b31a18b7a8a04d46a667ee165fd/core/jreleaser-model/src/main/java/org/jreleaser/model/ChocolateyBucket.java#L25-L27

https://github.com/jreleaser/jreleaser/blob/32cb7edda1af1b31a18b7a8a04d46a667ee165fd/core/jreleaser-model/src/main/java/org/jreleaser/model/JbangCatalog.java#L25-L27
