### ISSUE TITLE
[brew] `brew test-bot --only-tap-syntax` doesn't like a couple of things in produced formula file

### ISSUE THREAD

**Issue by itzg** [jreleaser/jreleaser#460]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Perform a successful homebrew publication
2. View the github actions from a repo created with `brew tap-new`, where it installs a test github workflow such as [this one](https://github.com/itzg/homebrew-tap/blob/65821931333033f7b4cfbb5383cf8474ffd47d5a/.github/workflows/tests.yml)

### Expected Behaviour

Expected the brew validation build to pass.

### Actual Behaviour

Validation fails [like this](https://github.com/itzg/homebrew-tap/runs/4061578261?check_suite_focus=true#step:7:21) when processing a jreleaser created formula file [such as this one](https://github.com/itzg/homebrew-tap/blob/81fd1557846008b6096030f912b3556228f01612/Formula/prune-branches.rb).

Admittedly I'm not totally sure what `test-bot` or `brew style` are doing there since it claims they're auto-corretable:

```
1 file inspected, 2 offenses detected, 2 offenses auto-correctable
Error: `url` (line 5) should be put before `version` (line 4)
Error: Final newline missing.
```

but I'm hoping it'll be happy after those two things are generated as it expects.

### Environment Information

- **Operating System**: Linux
- **JReleaser Version:** 0.8.0
- **JDK Version:** 17

[trace.log](https://github.com/itzg/prune-branches/suites/4214349372/artifacts/108895784)

> FYI this is the last of the issues I found on my homebrew publishing journey 😃

**Comment by aalmiray** [comment]
I wonder `test-bot` would say about a formula like this one https://gitea.com/gitea/homebrew-gitea/src/branch/master/gitea.rb

**Comment by aalmiray** [comment]
Thanks @itzg for the detailed reports. While the fixes that affect the Gradle plugin would require a new release (we don't release snapshot versions of plugins at the moment) you could test out some of the updates by using the CLI directly.

**Comment by itzg** [comment]
> you could test out some of the updates by using the CLI directly

Good point. I'm also fine waiting for 0.9.0 since I have the tweaks in place until I update to the DSL changes in 0.9.0.

**Comment by aalmiray** [comment]
OK, we usually post releases by the end of the month thus `v0.9.0` will come out during ThanksGiving weekend 😏
