### ISSUE TITLE
[changelog] Create and update CHANGELOG.md as separate file

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#461]
Some projects prefer keeping a separate CHANGELOG.md file with all entries per release, instead of listing them in each release page.

**Comment by gotson** [comment]
@aalmiray i was wondering if there's any chance this would get done sooner rather than later ? I'm really interested in this, and that would help me migrate from semantic-release. I have an existing changelog that was generated by each release done with semantic-release, and i would like to keep that when migrating over to JReleaser.

Some examples: https://github.com/junrar/junrar/blob/master/CHANGELOG.md https://github.com/junrar/junrar/blob/master/CHANGELOG.md

**Comment by aalmiray** [comment]
I think the last hurdle is identifying a comment section that may be used to anchor the next entry.

**Comment by gotson** [comment]
In the examples above, the changelog for the newest version is always added at the top, so there wouldn't be any need for that, right ?

**Comment by aalmiray** [comment]
Yes, but not all aggregated changelogs are equal. See https://github.com/helidon-io/helidon/blob/helidon-3.x/CHANGELOG.md

**Comment by gotson** [comment]
you're right, i agree. Do you actually need the anchor to ship the feature, or could it be done in 2 steps, first with append/prepend only, and later on have the anchoring feature?

**Comment by aalmiray** [comment]
If there's no anchor then it will prepend. How about that?

**Comment by aalmiray** [comment]
Released in v1.4.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.4.0

**Comment by jacobk** [comment]
Hey! Sorry for reviving this old thread.

How is the appended changelog best incorporated into the release-process. I guess jreleaser won't add+commit+push the appended changelog as part of doing a full-release? But if not, how can one ensure that the changelog update is part of the tagged commit?

**Comment by aalmiray** [comment]
You could configure a script hook (https://jreleaser.org/guide/latest/reference/hooks/script.html) to run on `success`, filtering by `changelog`. I'd recommend adding a condition (such as checking if running on CI or if the tool was not invoked in dryrun mode) as the hook would be invoked everytime the `changelog` step successfully completes.

**Comment by jacobk** [comment]
> You could configure a script hook (https://jreleaser.org/guide/latest/reference/hooks/script.html) to run on `success`, filtering by `changelog`. I'd recommend adding a condition (such as checking if running on CI or if the tool was not invoked in dryrun mode) as the hook would be invoked every time the `changelog` step successfully completes.

I see. Thanks!
