### ISSUE TITLE
[core] Unclear error message when no JRELEASER_GITHUB_TOKEN is defined.

### ISSUE THREAD

**Issue by michael-simons** [jreleaser/jreleaser#477]
The error message when no `JRELEASER_GITHUB_TOKEN` is set says:

```
[ERROR] == JReleaser ==
[ERROR] github.token must not be blank. Configure a value using the Maven DSL, or define a JRELEASER_GITHUB_TOKEN environment variable, or define a key/value pair in /Users/msimons/.jreleaser/config.properties
```

It is unclear whether `config.properties` takes `JRELEASER_GITHUB_TOKEN` or `github.token` (it takes the former).

**Comment by aalmiray** [comment]
Indeed. The key mist match the same name as the environment variable. Will fix the error message. Thanks!
