### ISSUE TITLE
Platform distributions: configuration by exception for path

### ISSUE THREAD

**Issue by ge0ffrey** [jreleaser/jreleaser#546]
It would be nice if instead of stating:
![Selection_937](https://user-images.githubusercontent.com/176880/143021364-c6b381a6-018c-4b0a-b66f-5abbaeee45ae.png)

if the `<path>` element would be optional, so we only have to specify `linux-x86_64, windows-x86_64, osx-x86_64`.

**Comment by aalmiray** [comment]
I can see the savings in configuration however is not that much. JReleaser could infer the filename based on the current distribution, project version, and platform. However it can't infer the extension (`zip`, `tar.gz`, etc), specially when both options happen to be available in the filesystem. More over, even if it could infer the filename without ambiguity it would still fall short of locating the file as the artifact path is not complete without it's containing directory. 

The current implementations enforces `path` to exist but `platform` and `transform` are optional properties. This feature would require treating all artifacts properties as optional depending on the context.

**Comment by aalmiray** [comment]
The `native-image` assembler can now fill out all potential artifact candidates when marked as `exported: true`. There's no longer a need to explicitly define artifact paths unless:
- additional extra properties per artifact are required
- a `transform` may bed required

Closing as completed in `v1.5.0`.
