### ISSUE TITLE
[changelog] Categories should be identifiable separatedly from their formatting

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#619]
Categories have a `title` property that's used to render them on the changelog, as well as matching and merging settings applied by presets. this poses a problem when the formatting includes special character such as spaces and emojis.

I'd be better if categories had a `key` (identifier) used for matching and keep the `title` for rendering. For backward compatibility the value of `key` will be set to `title` if `key` is not explicitly defined.

CC @michael-simons @kcpeppe

**Comment by aalmiray** [comment]
@michael-simons @kcpeppe please use the `key` property on a category to match customizations made to the changelog.

**Comment by michael-simons** [comment]
Thanks @aalmiray for the heads up, works nicely:

https://github.com/michael-simons/neo4j-migrations/commit/ffddee75ef17253dba2dd44e18fb312f9565ceb7
