### ISSUE TITLE
Add support for bash/zsh completion scripts in brew

### ISSUE THREAD

**Issue by yschimke** [jreleaser/jreleaser#625]
See 

https://github.com/michael-simons/neo4j-migrations/blob/main/etc/jreleaser/distributions/brew/formula.rb.tpl#L21

Mainly seems to add

```
    bash_completion.install "completion/neo4j-migrations_completion" => "neo4j-migrations"
    zsh_completion.install "completion/zsh/_neo4j-migrations" => "_neo4j-migrations"
```

I'm about to add the same for my project.

**Comment by aalmiray** [comment]
Further customizations for a particular packager file are the reason for using a templating system in the first case. For this reason you can invoke the `template` command and customize the generated template as you deem necessary.

You're asking to open the door for customizing the `install` block, which may be seen as:

1. customize the while block (including how the binary is copied to the destination)
2. customize just extra bits, leave binary copying as is.

I believe that for the time being generating your own template and adding the tweaks you need is enough.

**Comment by yschimke** [comment]
Sure, I'll close.  It seemed relevant as it's likely to be configured differently in some/all of the packagers. It was noticeable that I'm overriding the template for precisely the same reason as other users will be.
