### ISSUE TITLE
[brew] publisher tags without any prefix

### ISSUE THREAD

**Issue by yschimke** [jreleaser/jreleaser#638]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Use a common homebrew-tap for multiple jreleaser
2. release both projects

### Expected Behaviour

tags in the common homebrew project have prefix to differentiate them, or skipTags is available for 

### Actual Behaviour

https://github.com/yschimke/homebrew-tap/tags

Versions are mixed from different apps.

### Environment Information

- **Operating System**: linux
- **JReleaser Version:** 0.10.0
- **JDK Version:** 17

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

**Comment by aalmiray** [comment]
I see. The tap repository uses the same tag as the main repository. The tag is OK for the main but the tap may share with other formulas. This would also apply for other packagers that allow sharing such as Gofish, Scoop, Macports, Docker, JBang, Chocolatey.

The tap/bucket/repository should have it's own tag format, defaulting to the same format as the main repo if not set explicitly.

**Comment by yschimke** [comment]
Not blocking me, so mainly input to consider.
