### ISSUE TITLE
Ordering problem with jreleaserFullRelease and native image

### ISSUE THREAD

**Issue by yschimke** [jreleaser/jreleaser#640]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. ./gradlew jar installDist jreleaserFullRelease

Workaround is

1. ./gradlew jar installDist jreleaserAssemble
2. ./gradlew jreleaserFullRelease

### Expected Behaviour

The distribution is produced just in time during the jreleaserAssemble step.

### Actual Behaviour

https://github.com/yschimke/emulator-tools/runs/4662100990?check_suite_focus=true

```
[INFO]  Validating configuration

[ERROR] == JReleaser ==

[ERROR] Missing outputs for native-image.emulator-tools. Distribution emulator-tools has not been assembled
* Try:
```

### Environment Information

- **JReleaser Version:** 0.10.0
- **JDK Version:** 17

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

[trace.log](https://github.com/jreleaser/jreleaser/files/7790720/trace.log)

**Comment by aalmiray** [comment]
This is the intended behavior. The `assemble` step must be invoked separately from the other JReleaser tasks/goals.

The reasoning is this: distribution assembly should be performed by the build tool of choice. JReleaser provides convenience assemblies for archive, jlink, jpackage, and nativeImage, which should be treated as inputs coming from the build tool.

Also, the JReleaser `assemble` step does not have smart caching (yet) as Gradle offers. Intrinsically adding a dependency between `jreleaserAssemble` and `jreleaserChecksum` would make the build slower at this point.

**Comment by yschimke** [comment]
Thanks, that makes sense.  I missed the box to the left here https://jreleaser.org/guide/latest/workflow.html
