### ISSUE TITLE
Integrate with OpenTelemetry

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#646]
https://opentelemetry.io/

**Comment by kb-s** [comment]
Great work @aalmiray

**Comment by aalmiray** [comment]
The idea is to enable OTeL to provide tracing information similarly as it's done by https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/maven-extension/README.md

We may need to build this as an optional [extension](https://jreleaser.org/guide/early-access/extensions/index.html) as OTeL increases significantly the number of dependencies. An explicit extension point must be created for this feature.

cc: @cjudd

**Comment by aalmiray** [comment]
Moved to https://github.com/jreleaser/jreleaser-opentelemetry-extension/
