### ISSUE TITLE
[nativeImage] Assembler name is set to native-image

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#655]
It should match the same name as the YAML/TOML/JSON configuration that is, `nativeImage`.

**Comment by KlausBrunner** [comment]
I seem to have run into the same or a related issue, using jreleaser-maven-plugin:1.4.0. This call here gives me a warning:

```
mvn -Djreleaser.assemblers=nativeImage jreleaser:assemble

...
[INFO] Included assemblers: [nativeimage]
[WARNING] Unsupported assembler nativeimage
...
```

While this works, i.e. it starts the native image assembler:
```
mvn -Djreleaser.assemblers=native-image jreleaser:assemble
```

**Comment by aalmiray** [comment]
@KlausBrunner filed https://github.com/jreleaser/jreleaser/issues/1195
