### ISSUE TITLE
GitHub release fails on tag

### ISSUE THREAD

**Issue by charphi** [jreleaser/jreleaser#663]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a worflow on GitHub that calls the jrelease maven plugin
2. Dry-run release on branch develop
https://github.com/nbbrd/sandbox/blob/b86d7f0c0e40b453777004946f6dca6c6787c87f/.github/workflows/java8-maven.yml#L86
3. Release on tag 'v*'
https://github.com/nbbrd/sandbox/blob/b86d7f0c0e40b453777004946f6dca6c6787c87f/.github/workflows/java8-maven.yml#L131

Here is the maven configuration: 
```xml
<configuration>
    <jreleaser>
        <release>
            <github>
                <skipTag>true</skipTag>
                <draft>true</draft>
                <changelog>
                    <external>${project.basedir}/../CHANGELOG.md</external>
                </changelog>
            </github>
        </release>
    </jreleaser>
</configuration>
```

### Expected Behaviour

Should release as usual (was working with jreleaser 0.8.0 with fixed branch parameter)

### Actual Behaviour

Fails with the following message on tag:

```
Error:  Failed to execute goal org.jreleaser:jreleaser-maven-plugin:0.10.0:full-release (default) on project sandbox-binaries: Execution default of goal org.jreleaser:jreleaser-maven-plugin:0.10.0:full-release failed: 
Unexpected error when creating release: Unrecognized branch 'main'. Available branches are: [] -> [Help 1]
```

The available branches list is empty.

### Environment Information

- **Operating System**: Ubuntu
- **JReleaser Version:** 0.10.0
- **JDK Version:** 11

**Comment by aalmiray** [comment]
JReleaser sets the default branch to `main` and will check if that branch exist in the remote before committing.
In your case your repository has 2 branches: `develop`, `master`. you must explicitly configure which branch should be used, for example `<branch>master</branch>` otherwise `main` will be picked up for you.

**Comment by charphi** [comment]
I did that but it was complaining that `master` branch was unrecognized since not in the available branches.
Here is the error message I had when using `<branch>master</branch>` with dry-run release on develop:

```
Failed to execute goal org.jreleaser:jreleaser-maven-plugin:0.10.0:full-release (default) on project sandbox-binaries: Execution default of goal org.jreleaser:jreleaser-maven-plugin:0.10.0:full-release failed: 
Unexpected error when creating release: Unrecognized branch 'master'. Available branches are: [develop] -> [Help 1]
```

I then removed `<branch>master</branch>` and it worked on dry-run release on develop but failed on normal release on tag.

**Comment by aalmiray** [comment]
Yes, dryrun does not perform all remote operations and that's why the remote branch check does not occur. Let me have another look with a fork.

**Comment by aalmiray** [comment]
Well, just forking your project and invoking `mvn -Pfull-release install -DskipTests` worked on the first try https://github.com/aalmiray/sandbox/releases

The trace file contains

```
[INFO]  Releasing to https://github.com/aalmiray/sandbox
[DEBUG] looking up release with tag early-access at repository aalmiray/sandbox
[DEBUG] fetching release on aalmiray/sandbox with tag early-access
[DEBUG] release early-access does not exist
[DEBUG] creating release early-access
[DEBUG] deleting tag early-access from aalmiray/sandbox
[DEBUG] tagging local repository with early-access
[DEBUG] creating release on aalmiray/sandbox with tag early-access
[INFO]   - uploading hello-nbbrd-2.0.4-SNAPSHOT-bin.jar
[INFO]   - uploading hello-nbbrd-2.0.4-SNAPSHOT-bin.jar.sha256
[INFO]   - uploading hellow-nbbrd-2.0.4-SNAPSHOT-bin.jar
[INFO]   - uploading hellow-nbbrd-2.0.4-SNAPSHOT-bin.jar.sha256
[INFO]   - uploading checksums_sha256.txt
[INFO]   - uploading hello-nbbrd-2.0.4-SNAPSHOT-bin.jar.asc
[INFO]   - uploading hellow-nbbrd-2.0.4-SNAPSHOT-bin.jar.asc
[INFO]   - uploading checksums_sha256.txt.asc
```

**Comment by charphi** [comment]
Indead, it works on `develop` branch but fails on a pushed tag. I'm using the push tag event on GitHub to trigger a release.

**Comment by charphi** [comment]
I've just found the solution: 
Simply add the `fetch-depth: 0` option on the Checkout workflow step (as stated in your doc 😄 ) to make it work.

**Comment by aalmiray** [comment]
Oh? I thought that was a given, should had checked it before. This is perhaps one of the things I need to remark in the docs as a checklist before pushing your first release.

**Comment by charphi** [comment]
Anyway, thanks for you prompt help !
