### ISSUE TITLE
Cannot launch JReleaser on macOS installed via brew

### ISSUE THREAD

**Issue by ApfelSaucell** [jreleaser/jreleaser#675]
I downloaded jreleaser using:
1. Homebrew
2. Downloaded the pre-compiled binary from the releases page and uncompressed ..

when I run jrelease from the terminal I get:  
`zsh: killed     jreleaser -v`

Thanks for a great tool.

### Environment Information

- **Operating System**: OSX
- **JReleaser Version:** 0.10.0
- **JDK Version:** jdk11, jdk15, jdk17.

**Comment by aalmiray** [comment]
Direct download & unpack from https://github.com/jreleaser/jreleaser/releases/download/v0.10.0/jreleaser-standalone-0.10.0-osx-x86_64.zip works.

However installing from JReleaser's tap breaks.

**Comment by ApfelSaucell** [comment]
- still the same.  my operating system kills my process!
- any one else managed to run jreleaser in OSX Monterey? binaries or homebrew.

**Comment by aalmiray** [comment]
> still the same. my operating system kills my process!

Does this mean that directly downloading and unpacking fails for you on Monterey?

**Comment by aalmiray** [comment]
Directly unpacking the downloaded archive by brew (for example `unzip -d. /Users/aalmiray/Library/Caches/Homebrew/downloads/ad761b8fcddc501beeab2534ff3a59dc300d855a148e8b200b5456a179497ee5--jreleaser-standalone-0.10.0-osx-x86_64.zip`) and running `./jreleaser-standalone-0.10.0-osx-x86_64/bin/jreleaser -V` works which means the distribution is working as expected however the install procedure by the brew Formula may be broken.

I've reinstalled the xcode command line tools and still got the same `Killed: 9` error.

**Comment by ApfelSaucell** [comment]
> Directly unpacking the downloaded archive by brew (for example `unzip -d. /Users/aalmiray/Library/Caches/Homebrew/downloads/ad761b8fcddc501beeab2534ff3a59dc300d855a148e8b200b5456a179497ee5--jreleaser-standalone-0.10.0-osx-x86_64.zip`) and running `./jreleaser-standalone-0.10.0-osx-x86_64/bin/jreleaser -V` works which means the distribution is working as expected however the install procedure by the brew Formula may be broken.
> 
> I've reinstalled the xcode command line tools and still got the same `Killed: 9` error.

Solved :-)
== **Summary** ==
- Environment Information
   * Operating System: OSX - Montrerey
    * JReleaser Version: 0.10.0
    * JDK Version: jdk11, jdk15, jdk17.
- Homebrew is broken also when you reinstall xcode.
- I changed my security preferences: system preferences -> security & privacy -> General -> allow app store and identified developer.
- as @aalmiray mentioned, I downloaded the release:  https://github.com/jreleaser/jreleaser/releases/download/v0.10.0/jreleaser-standalone-0.10.0-osx-x86_64.zip and run it in the terminal `./jreleaser-standalone-0.10.0-osx-x86_64/bin/jreleaser -V`
- I could initiate new yaml and the whole release pipeline.

Thanks for the Tool, love you maaaan. looking forward for more stuff from you.

**Comment by aalmiray** [comment]
Just to be clear, direct download & unpack works for you, that's to be expected.
Changing security preferences made the brew package work?

**Comment by ApfelSaucell** [comment]
> Just to be clear, direct download & unpack works for you, that's to be expected. Changing security preferences made the brew package work?

- with brew I couldn't work, the OS always terminate the process !! also when I reinstalled xcode.
- by changing the security preference I could execute the unpacked download.
