### ISSUE TITLE
Use valid SPDX identifiers in the "init" templates

### ISSUE THREAD

**Issue by sualeh** [jreleaser/jreleaser#683]
Use valid SPDX identifiers in the "init" templates in 
"jreleaser/core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/init/"

See https://github.com/jreleaser/jreleaser/issues/545https://github.com/jreleaser/jreleaser/issues/545

**Comment by aalmiray** [comment]
That's right, it should be "Apache-2.0" instead of "Apache-2"
