### ISSUE TITLE
[core] Add a download step to complement assemble

### ISSUE THREAD

**Issue by sualeh** [jreleaser/jreleaser#728]
See https://github.com/jreleaser/jreleaser/discussions/727

Add an option to download assets required for assembly or release.

**Comment by aalmiray** [comment]
This should be a new workflow step without any dependencies nor dependents to other workflow steps, sch as `assemble`.

**Comment by aalmiray** [comment]
@gsmet this might be of interest to you as well. One more thing, JReleaser has launcher script templates (sh/bat) for jlink which are not exposed in any other way. I wonder if these templates should also be made visible as part of the `archive` assembler and/or yet another assembler. These two options would simplify the Quarkus CLI release.

**Comment by gsmet** [comment]
Yeah, I somehow expected that JReleaser would provide the scripts for me when I built the Java binary archives. It's probably a very common use case.
