### ISSUE TITLE
[chocolatey] licenseUrl is mandatory

### ISSUE THREAD

**Issue by gsmet** [jreleaser/jreleaser#733]
Apparently, having a `licenseUrl` defined for Chocolatey is mandatory:

```
PS D:\a\chocolatey-bucket\chocolatey-bucket> Chocolatey v0.12.0
LicenseUrl cannot be empty.
Error: Process completed with exit code 1.
```

Which is not exactly obvious.

**Comment by gsmet** [comment]
So FWIW, I have this in the output:
```
[WARN]      [chocolatey] Project does not define a value for licenseUrl
```
but a WARN is a bit light if in the end I can't release.

**Comment by aalmiray** [comment]
Got it. JReleaser would try its best to find a LICENSE file at the basedir such as it's done with its own releases

https://github.com/jreleaser/chocolatey-bucket/blob/f28a2116c39be8952c34c0bcf64bb84d64c6f126/jreleaser/jreleaser.nuspec#L24

However in your case I think JReleaser was configure in a module that's not at the root thus this check did not produce the expected result. I'll add an extra validation step for this value.

**Comment by gsmet** [comment]
Yes, I confirm we don't execute things at the root.

**Comment by aalmiray** [comment]
Yes, I can see the warning as well. Will add an extra check and turn the warning into an error if there's no valid URL.

**Comment by gsmet** [comment]
Thanks!
