### ISSUE TITLE
[chocolatey] Ability to override version

### ISSUE THREAD

**Issue by gsmet** [jreleaser/jreleaser#735]
Funny thing... Chocolatey doesn't support our version scheme:
```
PS D:\a\chocolatey-bucket\chocolatey-bucket> Chocolatey v0.12.0
'2.7.0.Final' is not a valid version string.
Parameter name: version
```
I don't see us changing our naming scheme anytime soon so I wonder if we could override the version that is injected here:
https://github.com/quarkusio/chocolatey-bucket/blob/main/quarkus/quarkus.nuspec#L8

I'll experiment but I think that's all that would be needed.

We need to be able to define it with a environment variable as we will need to script the suffix removal.

I can probably dedicate some time to get this in shape but I wanted to check if you thought it was the way to go or if there was some other options.

**Comment by aalmiray** [comment]
To get around this problem you can generate a chocolatey template

```
jbang jreleaser@jreleaser template -d quarkus -p chocolatey
```

Then edit the generated templates (probably just the nuspec template) and use any of the other name templates related to project version numbers https://jreleaser.org/guide/latest/configuration/name-templates.html#_project

you might end up with `{{projectVersionMajor}}.{{projectVersionMinor}}.{{projectVersionPatch}}` instead of just '{{projectVersion}}'.

**Comment by aalmiray** [comment]
The `jpackage` assembler lets you override the `appVersion` which also imposes restrictions on the format. while the proposed workaround with templates works it also makes sense to add a property to the DSL to override the version without having to use file templates.

**Comment by gsmet** [comment]
Yeah, problem is my templates will get out of date and there's a good chance I won't follow things closely to update them regularly.

For now I ended up with this ugly thing:
https://github.com/quarkusio/chocolatey-bucket/blob/main/.github/workflows/push.yml#L11-L14

But I'll add to my todolist to allow defining a version.

**Comment by aalmiray** [comment]
https://docs.chocolatey.org/en-us/create/create-packages#package-fix-version-notation

**Comment by aalmiray** [comment]
FWIW they may accept other tags as JReleaser `v1.0.0-M1` is listed https://community.chocolatey.org/packages/jreleaser/#versionhistory

I'll have to research more on version handling by chocolatey before committing to a fix.

**Comment by gsmet** [comment]
@aalmiray any chance it could also be set via an environment variable? Because I will need to do some magic to strip the `.Final` suffix.

**Comment by aalmiray** [comment]
@gsmet perhaps by enabling the use of `JRELEASER_CHOCOLATEY_PACKAGE_VERSION`, would that be OK with you?

**Comment by aalmiray** [comment]
@gsmet but before going the route of an env var you can do the following today after this fix was merged:

**jreleaser.yml**
```yaml
packagers:
  chocolatey:
    active: always
    packageVersion: '{{projectVersionMajor}}.{{projectVersionMinor}}.{{projectVersionPatch}}'
```

In other words, you don't have to pre-process the version, you can use name templates instead.

**Comment by gsmet** [comment]
That's perfect, then, thanks!

**Comment by aalmiray** [comment]
@gsmet alright. Let me know of this option works for you (give it a try with `jreleaser prepare -p chocolatey` and inspect `out/jreleaser/prepare/*`). If it's not enough then I'll add the env var.

**Comment by sualeh** [comment]
@aalmiray - I am getting a regression. I have defined the project "version" as "16.16.11", and it fails with the following exception. I tried defining the Chocolatey "packageVersion" as well, but it failed in the same way. Any thoughts?

```
jreleaser.shadow.org.jreleaser.util.JReleaserException: JReleaser has not been properly configured.
Invalid chocolatey package version 16.16.11. Follow SemVer with optional .number or .yyyyMMdd as tag

	at jreleaser.shadow.org.jreleaser.engine.context.ModelValidator.validate(ModelValidator.java:53)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.<init>(WorkflowImpl.java:42)
	at jreleaser.shadow.org.jreleaser.workflow.Workflows.fullRelease(Workflows.java:117)
	at jreleaser.shadow.org.jreleaser.cli.FullRelease.doExecute(FullRelease.java:144)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:81)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:38)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:47)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:29)
	at jreleaser.shadow.picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at jreleaser.shadow.picocli.CommandLine.access$1300(CommandLine.java:145)
	at jreleaser.shadow.picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at jreleaser.shadow.picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at jreleaser.shadow.picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at jreleaser.shadow.picocli.CommandLine.execute(CommandLine.java:2078)
	at jreleaser.shadow.org.jreleaser.cli.Main.execute(Main.java:72)
	at jreleaser.shadow.org.jreleaser.cli.Main.run(Main.java:68)
	at org.jreleaser.tool.JReleaser.main(JReleaser.java:45)
```

**Comment by aalmiray** [comment]
@sualeh thanks. Just pushed a fix, next early-access will be ready in half an hour. https://github.com/jreleaser/jreleaser/actions/runs/1801639117

**Comment by sualeh** [comment]
@aalmiray - thanks - your fix worked.

**Comment by gsmet** [comment]
@aalmiray I'm working on upgrading to `M2`. Are you sure you are applying the templating to the `packageVersion`?

I tried what you described above and I end up with:
```
[INFO]  JReleaser 1.0.0-M2
[INFO]  Configuring with jreleaser.yml
[INFO]    - basedir set to /data/home/gsmet/git/quarkus-release/work/quarkus/devtools/cli/distribution
[INFO]  Reading configuration
[INFO]  Loading variables from /home/gsmet/.jreleaser/config.properties
[INFO]  Validating configuration
[ERROR] == JReleaser ==
[ERROR] Invalid chocolatey package version {{projectVersionMajor}}.{{projectVersionMinor}}.{{projectVersionPatch}}. Follow SemVer with optional .number or .yyyyMMdd as tag
JReleaser has not been properly configured.
Invalid chocolatey package version {{projectVersionMajor}}.{{projectVersionMinor}}.{{projectVersionPatch}}. Follow SemVer with optional .number or .yyyyMMdd as tag
```

So I suspect the templating is not applied before checking the version.

**Comment by aalmiray** [comment]
I'm seeing the same error in `1.0.0-M2` and `1.0.0-SNAPSHOT` at the moment.
Please use an explicit value for the time being.
