### ISSUE TITLE
Chocolatey - Remote build - .github/workflows directory added in subdirectory

### ISSUE THREAD

**Issue by gsmet** [jreleaser/jreleaser#742]
Hi,

I just made a new `quarkus` release and JReleaser created this weird commit:
https://github.com/quarkusio/chocolatey-bucket/commit/cfd530c28c7a16a3a7e203efb9e9c108485db450

As you can see, it somehow added the workflows I have in the repository in the `quarkus` subdirectory.

The only change I made recently was to define: `export JRELEASER_CHOCOLATEY_GITHUB_BRANCH=${BRANCH}`. I thought it would push the new version in a branch and apparently it does not as things were pushed in `main` anyway.

Also I might have upgraded to 1.0.0-M1 recently.

It looks weird enough that I might have done something I shouldn't have done but I have no idea what.

Our JReleaser setup for 2.7 is here: https://github.com/quarkusio/quarkus/tree/2.7/devtools/cli/distribution .

**Comment by aalmiray** [comment]
Yes, we spotted this issue and fixed it in the upcoming `v1.0.0-M2`. Apologies for the mess. You can manually move the files from the subdir into their correct location and manually trigger a build with the `trigger.yml` workflow. https://github.com/jreleaser/jreleaser/issues/704

**Comment by aalmiray** [comment]
Ah that was yet another error in the templates due to the use of {{ by Mustache. The src template is https://github.com/jreleaser/jreleaser/blob/main/core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/java-binary/chocolatey/.github/workflows/trigger.yml.tpl

Adjusting the file should result in a secret such as `${{ secrets.CHOCOLATEY_API_KEY }}`.

**Comment by aalmiray** [comment]
Also, the current behavior for tap/bucket repos is to just tag the latest push that's performed to the default HEAD. Would you like to customize this behavior and have the code be pushed to a branch? That would also affect the convenience GH workflows btw.

**Comment by gsmet** [comment]
Yes, I was thinking about using that feature and build the appropriate branch manually. Mostly because we are not really ready to automate Chocolatey (our first version was not approved yet).

But the tag thing is perfect IMHO. And I can live with the builds failing for now.
