### ISSUE TITLE
[jpackage] Can't use JFXCentral as application name

### ISSUE THREAD

**Issue by dlemmermann** [jreleaser/jreleaser#751]
I currently can not use upper case "JFXCentral" as the application name as this will collide with naming conventions for linux packages. As a temporary workaround the application uses the name "jfxcentral" (all lower case).

**Comment by aalmiray** [comment]
The problem occurs on Linux when assembling a `.deb` installer

https://github.com/dlemmermann/jfxcentral/runs/5175175311?check_suite_focus=true
```
Bundler DEB Bundle failed because of java.lang.IllegalArgumentException: jdk.jpackage.internal.ConfigException: Invalid value "JFXCentral" for the bundle name.
```
