### ISSUE TITLE
[core] After upgrading to M2, getting "licenseUrl" error when trying to run jreleaserConfig

### ISSUE THREAD

**Issue by bitspittle** [jreleaser/jreleaser#757]
With this jreleaser config: https://github.com/varabyte/kobweb/blob/00a051b6fdfd9fb497ed77b0f33f4b4eae58e451/cli/kobweb/build.gradle.kts#L40

```
> Task :cli:kobweb:jreleaserConfig FAILED
[INFO]  JReleaser 1.0.0-M2
[INFO]    - basedir set to /home/d9n/Code/1p/kobweb/cli/kobweb
[INFO]  Loading variables from /home/d9n/.jreleaser/config.properties
[WARN]  Variables source /home/d9n/.jreleaser/config.properties does not exist
[INFO]  Validating configuration
[ERROR] == JReleaser ==
[ERROR] Project does not define a value for licenseUrl

Execution failed for task ':cli:kobweb:jreleaserConfig'.
> JReleaser has not been properly configured.
  Project does not define a value for licenseUrl

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':cli:kobweb:jreleaserConfig'.
   ...
Caused by: org.jreleaser.util.JReleaserException: JReleaser has not been properly configured.
Project does not define a value for licenseUrl

	at org.jreleaser.engine.context.ModelValidator.validate(ModelValidator.java:53)
	at org.jreleaser.gradle.plugin.tasks.JReleaserConfigTask.displayConfig(JReleaserConfigTask.groovy:67)
```

I saw a closed issue saying that `licenseUrl` is required for chocolately but I'm not using that package manager.

---

As a side note, maybe the docs for `licenseUrl` can be updated to include an example?

It is just a link to the license in my github project? If so, can it default to github/LICENSE if not present and targeting a github project?

Or is it something like `http://www.apache.org/licenses/LICENSE-2.0` at which point, can JReleaser generate these for known `license` values? (My `license` property is set to "Apache-2.0" for example)

Finally, there's a small typo: **the URL ofmthe project license** <-- remove the "m"

**Comment by aalmiray** [comment]
The`licenseUrl` element is defined at https://docs.microsoft.com/en-us/nuget/reference/nuspec#licenseurl

It has been deprecated in favor of `license` however Chocolatey does not like `license` and prefers `licenseUrl` 🤷‍♂️ 

Currently JReleaser attempts to resolve a license file named "LICENSE", "LICENSE.txt", "LICENSE.adoc", or "LICENSE.md" residing at the root of the project. If such file is found then it'll setup a raw git URL to the file. See https://github.com/jreleaser/chocolatey-bucket/blob/927e24fc66df285a36c3e5f010ee7527e3323db8/jreleaser/jreleaser.nuspec#L24 

It could be possible to generate a license URL for a given license ID that follows SPDX identifiers. Also when used as a Maven plugin, as the license URL is usually a given, sadly that's not the case for Gradle as there's no standard setting for license information.

Please feel free to open a ticket requesting license ID to license URL mapping.
