### ISSUE TITLE
Handle quiet mode

### ISSUE THREAD

**Issue by yschimke** [jreleaser/jreleaser#768]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run a build with `./gradlew -q ...`
2. observe only output is from jreleaser

### Expected Behaviour

No output in quiet mode

### Actual Behaviour

signing.args has been deprecated since 1.0.0-M1 and will be removed in the future. Use signing.command.args instead
signing.args has been deprecated since 1.0.0-M1 and will be removed in the future. Use signing.command.args instead

plus a patreon message.

### Environment Information

- **Operating System**: OSX M1
- **JReleaser Version:** 1.0.0-M1
- **JDK Version:** 17

**Comment by aalmiray** [comment]
Deprecation warnings will disappear once `v1.0.0` comes out. 

The patreon banner appears in the first 3 invocations of the plugin, although it might be a recurrent output on CI if the `~/.jreleaser` is not cached.

This being said, having a "quiet" mode in core which may be activated via its executing interfaces (cli, maven, gradle, ant) is a good idea.

**Comment by aalmiray** [comment]
Moreover, the cli already has a `quiet` flag which as it turns out activates the ERROR log level. It'll have to be remapped.

**Comment by yschimke** [comment]
This is not critical, but the reason it's relevant for me, is that for my CLI the release build is with native image.

But for quick development I have a command line script checked into github to build with gradle and then run.

https://github.com/yschimke/okurl/blob/main/okurl

**Comment by aalmiray** [comment]
Got it. I can work sometime out soon.
