### ISSUE TITLE
[chocolatey] Cannot parse packageVersion template

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#773]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure `chocolatey` on a project using a custom packageVersion such as `{{projectVersionMajor}}.{{projectVersionMinor}}.{{projectVersionPatch}}`
2. Prepare a distribution

### Expected Behaviour

Successful build

### Actual Behaviour

JReleaser fails with

```
[INFO]  Validating configuration
[ERROR] == JReleaser ==
[ERROR] Invalid chocolatey package version {{projectVersionMajor}}.{{projectVersionMinor}}.{{projectVersionPatch}}. Follow SemVer with optional .number or .yyyyMMdd as tag
JReleaser has not been properly configured.
Invalid chocolatey package version {{projectVersionMajor}}.{{projectVersionMinor}}.{{projectVersionPatch}}. Follow SemVer with optional .number or .yyyyMMdd as tag
```

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.0.0-M2
- **JDK Version:** N/A

Reported by @gsmet at https://github.com/jreleaser/jreleaser/issues/735#issuecomment-1048195302

**Comment by gsmet** [comment]
Thanks!
