### ISSUE TITLE
JReleaser pushed homebrew changes out with wrong openjdk

### ISSUE THREAD

**Issue by bitspittle** [jreleaser/jreleaser#785]
My code depends on JDK11, but as you can see here:
https://github.com/varabyte/homebrew-tap/commit/87fc3ffe333e7592f07939cbdb4e5ce0244f5bca
```
class Kobweb < Formula
...
  url "https://github.com/varabyte/kobweb/releases/download/cli-v0.9.7/kobweb-0.9.7.zip"
...
  depends_on "openjdk@16"
  ^^^^^^^^^^^^^^^^^^^^^^^
...
```
when I ran `jreleaserPublish` today, it updated my openjdk version to 16.

_Side note: It turns out that homebrew complains about openjdk@16, apparently that tag doesn't exist?_

What's strange is, after I noticed this, I locally ran `jreleaserConfig` and the output is normal:

https://pastebin.com/C8ejEVPT

You can see there my Java version is correctly identified as "11"

What's extra strange is I was going to try to repeat this for you today, but when I explicitly ran `jreleaserPackage`, it worked locally. The `kobweb.rb` file generated had `opendjk@11` marked correctly.

I'm not sure what happened, but I thought I'd go ahead and open a bug now since it *did* happen, and if it happened to me, it might be able to happen to others. 

That said, I can't reproduce it, so unless you have a hunch about what's going on, I'm not sure if this is a common edge case or extremely rare one.

---

My jreleaser config for reference, in case it matters: https://github.com/varabyte/kobweb/blob/9b04625c12a0abf89ed6e7e593881a6f90aa81ba/cli/kobweb/build.gradle.kts#L40

and where I define my Java versions: https://github.com/varabyte/kobweb/blob/9b04625c12a0abf89ed6e7e593881a6f90aa81ba/build.gradle.kts#L20

**Comment by aalmiray** [comment]
Were you able to capture the `trace.log`?

**Comment by aalmiray** [comment]
The value is set as a name template here

https://github.com/jreleaser/jreleaser/blob/b658a47605e3703e313b35d5c0f5e26f90f14aae/core/jreleaser-tools/src/main/java/org/jreleaser/packagers/BrewPackagerProcessor.java#L196-L200

The version value is taken from here 

https://github.com/jreleaser/jreleaser/blob/b658a47605e3703e313b35d5c0f5e26f90f14aae/core/jreleaser-model/src/main/java/org/jreleaser/model/Distribution.java#L114

Whose value is set during validation

https://github.com/jreleaser/jreleaser/blob/b658a47605e3703e313b35d5c0f5e26f90f14aae/core/jreleaser-model/src/main/java/org/jreleaser/model/validation/DistributionsValidator.java#L223-L225

Which is fed automatically by the Gradle plugin here

https://github.com/jreleaser/jreleaser/blob/b658a47605e3703e313b35d5c0f5e26f90f14aae/plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/JReleaserProjectConfigurer.groovy#L320-L332

As you can appreciate the value is taken from project properties `targetcompatibility` or `compilerRelease`. If neither is explicitly defined (on time) then the current JVM is used.

Did you run the build with JDK16?
Does your customization https://github.com/varabyte/kobweb/blob/9b04625c12a0abf89ed6e7e593881a6f90aa81ba/build.gradle.kts#L20 run _before_ JReleaser configures the model?

In any case you can explicitly set the value of `project.java.version` to avoid guessing.

**Comment by bitspittle** [comment]
So I figured out my repro case. Basically, the behavior changes when I use IntelliJ vs the command line. I set my IntelliJ project up to use Java 11 but I guess gradle externally is finding my Java 16 installation.

As you can see from my output: [output.txt](https://github.com/jreleaser/jreleaser/files/8163372/output.txt) the targetCompatibility version is getting set before the jreleaser task is called.

I need to run here in a bit, so I'm not 100% sure how to configure Gradle command line's java (I don't have JAVA_HOME set on my machine, so I forget how it's actually finding Java). Still, if you had JDK16 installed on your machine, you could possibly see this for yourself by cloning Kobweb and

0) edit gradle/libs.versions.toml, remove the "-SNAPSHOT" suffix from the "kobweb-cli" [versions] entry
1) run ./gradlew :cli:kobweb:jreleaserPackage from the command line
2) opening Kobweb in IntelliJ and run the "cli/jreleaser/jreleaserPackage" Gradle task

I will set the value of Java explicitly however for now :) I think that's a reasonable workaround (and would even be OK with you closing the bug)

**Comment by aalmiray** [comment]
FWIW defining a `targetCompatibility` property in `gradle.properties` should be enough regardless of the JDK used to run the build, for example

**gradle.properties**
```
targetCompatibility = 11
```

Supposedly the `java-base` plugin will pick this property automatically and every submodule will inherit if set at the root level.

**Comment by aalmiray** [comment]
And then I get to eat my own words because we already make use of `afterEvaluate` to configure the model

https://github.com/jreleaser/jreleaser/blob/b658a47605e3703e313b35d5c0f5e26f90f14aae/plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/JReleaserPlugin.groovy#L53-L65

Somehow I still think this is a timing issue. will have to dig deeper.

**Comment by bitspittle** [comment]
:)

Well good luck, and feel free not to prioritize this issue since there's a trivial workaround. I've added the Java version explicitly in my jreleaser config and am happy with the situation.

**Comment by aalmiray** [comment]
Right. I don't think there's much to do other than ensuring a project has explicit settings for `targetCompatibility`. The [enforcer-gradle-plugin](https://github.com/kordamp/enforcer-gradle-plugin/) has a rule for that: [RequireJavaVersion](https://kordamp.org/enforcer-gradle-plugin/#_requirejavaversion).
