### ISSUE TITLE
[chocolatey] packageSourceUrl fails when remoteBuild = false

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#799]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure the chocolatey packager with remoteBuild = false
2. Publish the package to the chocolatey push server

### Expected Behaviour

Successful package publication

### Actual Behaviour

Chocolatey complains that packageSourceUrl is invalid. This is because it points to an URL that does not exist.

### Environment Information

- **Operating System**: Windows
- **JReleaser Version:** 1.0.0-M3
- **JDK Version:** N/A

cc: @sualeh

https://github.com/jreleaser/jreleaser/discussions/798

**Comment by sualeh** [comment]
cc: @adriens
