### ISSUE TITLE
[core] Cannot parse version '2000.0.0[.A]' with 'YYYY.MINOR.MICRO[.MODIFIER]'

### ISSUE THREAD

**Issue by marceloverdijk** [jreleaser/jreleaser#803]
I'm getting a `Cannot parse version '2000.0.0[.A]' with 'YYYY.MINOR.MICRO[.MODIFIER]'` using the latest `1.0.0-RC1`:

```
> Task :jreleaserFullRelease
[INFO]  JReleaser 1.0.0-RC1
[INFO]    - basedir set to /home/runner/work/f1db/f1db
[INFO]  Loading variables from /home/runner/.jreleaser/config.properties
[WARN]  Variables source /home/runner/.jreleaser/config.properties does not exist
[INFO]  Validating configuration

[INFO]  Project version set to 2022.2.0
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jreleaserFullRelease'.
> Cannot parse version '2000.0.0[.A]' with 'YYYY.MINOR.MICRO[.MODIFIER]'
```

See full logs: https://github.com/f1db/f1db/runs/5715708834?check_suite_focus=true

This seems to be a regression with `1.0.0-M3` as in that version is works.
I just reverted back to `M3` and could successfully release.

**Comment by aalmiray** [comment]
Bug caused when assigning a default value given a format with optional modifier.
