### ISSUE TITLE
[changelog] Commit message not properly parsed on Windows

### ISSUE THREAD

**Issue by ohubaut** [jreleaser/jreleaser#804]
When extracting the commit title and commit body in ChangelogGenerator#of, line 589, the split incorrectly use the System.lineSeparator() function.
Unfortunately if commit message uses the linux encoding, the whole message is considered as title, and the body is empty.

As a side effect, the StringUtils#normalizeRegexPattern might append a ".*" to the end of the regex, which won't match the "\n", resulting in no label being applied on commits.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. On a Windows box:
2. Create a repository on windows, make some commits using conventional commits layout
3. Configure jreleaser with the conventional commits preset
4. Generate the changelog

### Expected Behaviour

The changelog should be properly categorized

### Actual Behaviour

None of the label are applied and the changelog is raw

### Environment Information

- **Operating System**: Windows
- **JReleaser Version:** 1.0.0-M3
- **JDK Version:** 17

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

**Comment by aalmiray** [comment]
@ohubaut please let me know if the latest early-access build solved the issue for you. You'll have yo run it as a CLI option.
