### ISSUE TITLE
[brew] Cannot run JReleaser after install

### ISSUE THREAD

**Issue by ixchelruiz** [jreleaser/jreleaser#818]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Requires an MBP with **Apple Silicon (M1)**
1. Install JReleaser using brew as per instructions
` brew install jreleaser/tap/jreleaser`
2. Run the installer binary 

### Expected Behaviour

JReleaser prints out its usage message.

### Actual Behaviour

The process is killed
```
$ /opt/homebrew/Cellar/jreleaser/1.0.0/bin/jreleaser
[1]    4000 killed     /opt/homebrew/Cellar/jreleaser/1.0.0/bin/jreleaser
```

### Environment Information

- **Operating System**: OSX
- **JReleaser Version:** 1.0.0
- **JDK Version:** N/A

**Comment by gastaldi** [comment]
Seems to be a problem with the `java` in `/opt/homebrew/Cellar/jreleaser/1.1.0/libexec/bin/java`, that binary seems be corrupted?

**Comment by aalmiray** [comment]
It's brew alright. If you download the `jreleaser-standalone` for `osx-aarch` zip and uncompress you should be able to run the tool without a problem. 

We had a similar problem with dynlib relocation on x86 macs.

**Comment by gastaldi** [comment]
Actually in M1 if I download the standalone ZIP I get the same error because it says that the `java` binary is from an untrusted source. Is there a distribution that reuses an already installed JRE instead?

**Comment by aalmiray** [comment]
You may need to remove the quarantine attrs first. The regular zip (such as `jreleaser-1.1.0.zip` should work as it does not bundle a JR. The reason to use the standalone archive is to skip a pre installed JR.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.8.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.8.0))

**Comment by haydenbaker** [comment]
We follow a similar release process for our CLI in homebrew as JReleaser. We had the same issue as you in the past for arm-based macs where we needed to re-codesign, but we recently hit the issue with x86 macs too. Just as a heads up, I'd recommend checking to see if this is an issue: https://github.com/smithy-lang/homebrew-tap/pull/8

**Comment by aalmiray** [comment]
Did you try using JReleaser `1.8.0`?

**Comment by haydenbaker** [comment]
Sorry, I didn't mean to insinuate that this is an _actual_ issue with JReleaser. I was just giving you a heads-up that _we_ hit the same problem with x86 macs (not just arm).

**Comment by aalmiray** [comment]
Note. Thank you for the heads up. Will have to review the latest formulas we posted. Is there an specific macOs version that should be uses for tests?

**Comment by haydenbaker** [comment]
We experienced the issue with x86-macs on Ventura 13.4, but YMMV. It wasn't an issue at first, but a couple months after we made the change to re-codesign for arm-based macs, the same exact issue manifested for x86-based macs.
