### ISSUE TITLE
[release] Comment on resolved issues/PRs when releasing

### ISSUE THREAD

**Issue by gotson** [jreleaser/jreleaser#904]
**Is your feature request related to a problem? Please describe.**
I would like JReleaser to comment on all the Github issues/PRs that are included in the release to announce that it has effectively been released, and in which release.

In addition, the label `released` is added.

semantic-release does that, here is an example comment [on an issue](https://github.com/gotson/komga/issues/940#issuecomment-1219007931) and [on a PR](https://github.com/gotson/komga/pull/949#issuecomment-1219007866).

This gives clarity on what has been released or not. Issues are closed when the associated commit is pushed to master/main, and PRs are closed when merged, but there is no indication that this has been released, or in which version.

The release notes would provide this information of course, but by adding a comment directly on the ticket, someone who subscribed to that particular issue can get a notification that a release is ready, containing the fix.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
semantic-release does that outside the box.

**Additional context**

**Comment by aalmiray** [comment]
JReleaser would have to perform the following tasks:

- [ ] Check if the `released` label exists, otherwise create it.
- [ ] Collect all issues mentioned in the changelog.
- [ ] For each collected issue:
 - Check if it has the `released` label. If so, skip it.
 - Add the `released` label.
 - Post a comment pointing to the release.

**Comment by gotson** [comment]
> Collect all issues mentioned in the changelog.

I think this relates to https://github.com/jreleaser/jreleaser/issues/806

**Comment by aalmiray** [comment]
Released in v1.3.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.3.0
