### ISSUE TITLE
[changelog] Explicitly warn when computing a change log on a shallow clone

### ISSUE THREAD

**Issue by fbiville** [jreleaser/jreleaser#910]
Some people (like me) do not read the documentation carefully (can you imagine?!) and miss the fact that JReleaser will fail when generating a change log against a shallow clone.
While this is obvious in retrospect, this is easy to miss, since some CI environments perform shallow clones by default.
Moreover, the error message is not 100% explicit (in retrospect, it makes sense though):
```
Unexpected error when creating release: Unrecognized branch 'main'. Available branches are: []
```

Since there is a way to detect shallow clones (see https://stackoverflow.com/questions/37531605/how-to-test-if-git-repository-is-shallow), it would be nice to issue at least an explicit warning (after all, the clone may be "deep" enough for the computation) when computing change log on shallow clones?
Maybe another option would be to allow the change log computation to become completely independent from the local clone.

**Comment by aidenzzz** [comment]
Hi,
I would love to work on this if help is still needed.
Thanks,
Aiden

**Comment by aalmiray** [comment]
@aidenzzz very well, thank you for stepping up! 😄 

Changes should be added (at least) to these classes:

Instance method that checks if the current repository is shallow
https://github.com/jreleaser/jreleaser/blob/main/sdks/git-sdk/src/main/java/org/jreleaser/sdk/git/GitSdk.java

Add a check here. Log a warning when repository is shallow
https://github.com/jreleaser/jreleaser/blob/main/sdks/git-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java#L181

**Comment by aidenzzz** [comment]
JGit does not seem to support checking if a repo is shallow or not. Would checking if`./.git/shallow` exists be the easiest way to determine if the repo is shallow?

**Comment by aalmiray** [comment]
That might do the trick.
