### ISSUE TITLE
lgtm reports 2 warnings as Potential input resource leak

### ISSUE THREAD

**Issue by diakogiannis** [jreleaser/jreleaser#922]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Go to <https://lgtm.com/projects/g/jreleaser/jreleaser/alerts?mode=list> 
2. The warnings are listed for the file Signer.java 

### Expected Behaviour

There should be no warnings

### Actual Behaviour

There are 2 warnings

### Environment Information

n/a

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.
n/a

**Comment by diakogiannis** [comment]
If it ok I will start working on these warnings

**Comment by aalmiray** [comment]
Alexius, those 2 warnings are false positives

**Comment by diakogiannis** [comment]
Closed as false positives
