### ISSUE TITLE
[core] Template name `projectNameCapitalized` does not replace hyphens by spaces

### ISSUE THREAD

**Issue by gastaldi** [jreleaser/jreleaser#923]
The [`projectNameCapitalized` template name](https://jreleaser.org/guide/latest/configuration/name-templates.html#_project) states that the project name is capitalized and hyphens are replaced by spaces, however, I am seeing a different output:

I have a project with the `<artifactId>` set to `quarkiverse-parent` and it outputs `QuarkiverseParent` (without any spaces).

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. `git clone https://github.com/quarkiverse/quarkiverse-parent.git`
2. Checkout the `jreleaser` branch: `git checkout jreleaser`
3. `export JRELEASER_ZULIP_API_KEY=foo` (it doesn't matter which value you use, the property is used in the topic subject and it's written in the build logs when the next step is executed)
4. Run `mvn jreleaser:announce`

You should see an output similar to:
```bash
[INFO]
[INFO] -----------------< io.quarkiverse:quarkiverse-parent >------------------
[INFO] Building Quarkiverse: Parent POM 11-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- jreleaser-maven-plugin:1.2.0:announce (default-cli) @ quarkiverse-parent ---
[INFO] JReleaser 1.2.0
[INFO]   - basedir set to /Users/ggastald/workspace/quarkiverse/quarkiverse-parent
[INFO] Loading variables from /Users/ggastald/.jreleaser/config.properties
[WARNING] Variables source /Users/ggastald/.jreleaser/config.properties does not exist
[INFO] Validating configuration
[INFO] Project version set to 11-SNAPSHOT
[INFO] Release is snapshot
[INFO] Timestamp is 2022-08-29T14:44:24.789182-03:00
[INFO] HEAD is at 58bc361
[INFO] Platform is osx-aarch_64
[INFO] dry-run set to false
[INFO] Generating changelog: target/jreleaser/release/CHANGELOG.md
[INFO] Announcing release
[INFO]   [zulip] channel: announce
[INFO]   [zulip] subject: QuarkiverseParent release
```

### Expected Behaviour

The `projectNameCapitalized` should output `Quarkiverse Parent` 

### Actual Behaviour

It outputs `QuarkiverseParent` 

### Environment Information

- **Operating System**: macOS 12.5.1
- **JReleaser Version:** 1.2.0
- **JDK Version:** 17

**Comment by aalmiray** [comment]
Released in v1.3.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.3.0
