### ISSUE TITLE
[changelog] Contributor exclusion regex does not work

### ISSUE THREAD

**Issue by fbiville** [jreleaser/jreleaser#957]
### Steps to Reproduce

Configure a contributor name such as `.*bot` or `*bot`.

### Expected Behaviour

This should exclude contributors such as `liquibot` or `dependabot`.

### Actual Behaviour

This is not the case. Both contributors are still listed.

Only the expression `bot` seems to work.

Feel free to try with https://github.com/liquibase/liquibase-neo4j/ (`mvn jreleaser:changelog -Prelease`).

### Environment Information

- **Operating System**: Mac OS 12.6
- **JReleaser Version:** 1.2.0
- **JDK Version:** Java 17.0.3 / Azul
- **Maven version**: 3.8.6

**Comment by aalmiray** [comment]
The bug is here https://github.com/jreleaser/jreleaser/blob/0e835d3145dddd055d959cf5d951294567ec7b3b/core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/release/Changelog.java#L943

The regex should not be escaped but rather use as is.
