### ISSUE TITLE
Provide a JSON Schema for the configuration

### ISSUE THREAD

**Issue by ohubaut** [jreleaser/jreleaser#964]
**Is your feature request related to a problem? Please describe.**
When writing a new configuration file, being in YAML or JSON, I always have to look back in the documentation to get list of available options as well as the overall structure. It would be nice if my tooling could provide me with some auto-completion and documentation directly.

**Describe the solution you'd like**
Providing a JSON Schema would allow for automatic completion as well as documentation for the whole configuration file. It would also automatically spot typos and invalid structures.
As an extra bonus, in case of breaking changes in the configuration file, validating it with the new schema would immediately indicate the portions that need to be migrated.

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by aalmiray** [comment]
You can obtain a copy of the json-schema by running the `json-schema` command from the CLI. https://jreleaser.org/guide/latest/tools/jreleaser-cli.html#_json_schema

**Comment by ohubaut** [comment]
Oh great! I missed that section.

Thanks!
