### ISSUE TITLE
Integrate with JFR

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#967]
https://developers.redhat.com/blog/2020/08/25/get-started-with-jdk-flight-recorder-in-openjdk-8u#the_jdk_flight_recorder_api

Ideas:

- trigger start/end events for each workflow step in the execution (i.e, changelog, checksum, release, etc)
- disabled by default when running with JVMs that do not support JFR

Questions:
- JReleaser offers many options for running the CLI, one of them is via native executables built with GraalVM Native Image. Any concerns with setting up and running JFR in this mode?

cc: @gunnarmorling @jonatan-ivanov

**Comment by gunnarmorling** [comment]
>  via native executables built with GraalVM Native Image. Any concerns with setting up and running JFR in this mode?

Nope, this should just work (TM). The JFR recording engine is available in native binaries by now, and while most built-in event types are not supported yet, custom ones -- like the case with the JReleaser events -- are.

**Comment by aalmiray** [comment]
@gunnarmorling thank you for confirming. We might get a chance to test custom events via JfrUnit 😉

**Comment by gunnarmorling** [comment]
Ha yeah, most certainly. That would be cool!

**Comment by aalmiray** [comment]
This has been moved outside of jreleaser/jreleaser. See https://github.com/jreleaser/jreleaser-jfr-extension
