### ISSUE TITLE
[build] Configure osx-aarch64  binaries

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#979]
GitHub just enabled osx arm64 runners. 

https://github.com/mthmulders/mcs

cc: @mthmulders

**Comment by mthmulders** [comment]
In fact, I use a self-hosted runner that I spin up whenever I need it. Works good enough for me...

**Comment by aalmiray** [comment]
Thanks. Sadly this wont't work all the time for out use case 😢

**Comment by aalmiray** [comment]
Already done a couple of releases ago.
