### ISSUE TITLE
[package] Error packaging Docker image with single-jar distribution 

### ISSUE THREAD

**Issue by jruaux** [jreleaser/jreleaser#982]
With a single-jar distribution the following error occurs in the Docker image build:
`can't create directory '/myapp/': Not a directory`

This seems to be caused by a clash between target assembly subdirectory and executable names. Both default to `{{distributionName}}`) in the [Dockerfile template](https://github.com/jreleaser/jreleaser/blob/main/core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/single-jar/docker/Dockerfile.tpl) so `mkdir` fails:

```
COPY assembly/ /

RUN mkdir -p /{{distributionName}}/bin && \
```

Workaround is simple enough (set executable name for the distribution) but it would be nice to have it work with defaults.

**Comment by aalmiray** [comment]
Released in v1.3.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.3.0
