### ISSUE TITLE
[build] Update use of set-output in workflows

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#983]
GitHub Actions will issue a warning when `::set-output` is used. Switch to new syntax as suggested at https://hynek.me/til/set-output-deprecation-github-actions/

**Comment by himanshukandpal-28** [comment]
Hey folks can I pick up the issue?

**Comment by aalmiray** [comment]
Sure, go ahead. Please remember to follow our contribution guidelines. Thanks! 😅

**Comment by himanshukandpal-28** [comment]
Hey @aalmiray raised the PR for the issue.

**Comment by aalmiray** [comment]
@himanshukandpal-28 thanks! However PR #984 appears closed before merging. Was that intentional?

**Comment by himanshukandpal-28** [comment]
> @himanshukandpal-28 thanks! However PR #984 appears closed before merging. Was that intentional?

Oh yes, actually I was testing then saw that these workflow only runs on main branch so rather than using side branch I moved my changes to main, https://github.com/jreleaser/jreleaser/pull/985, this is the one with all changes.

**Comment by aalmiray** [comment]
Released in v1.3.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.3.0
