### ISSUE TITLE
project.copyright should not be required

### ISSUE THREAD

**Issue by evanchooly** [jreleaser/jreleaser#995]
It's not required for maven central, e.g., and so I have it configured in exactly 0 projects.  If it's required by some deployment target, wouldn't it make more sense to validate there rather than , e.g., `jreleaser:config` ?

I'm a grump but in the meantime i'll add it because it want to get things done.  :)

my pom (so far):
```xml
            <plugin>
                <groupId>org.jreleaser</groupId>
                <artifactId>jreleaser-maven-plugin</artifactId>
                <version>1.2.0</version>
                <configuration>

                </configuration>
            </plugin>

```

**Comment by evanchooly** [comment]
none of the examples run in to this so it's clearly me.  let me play some more.  :)

**Comment by aalmiray** [comment]
FWIW I think `<inceptionYear>` is required by Maven Central. Copyright is inferred based on `author(s)` (deduced by looking at `<developers>`) and `<inceptionYear>`.

**Comment by evanchooly** [comment]
I've never used it fwiw
